import React, { useEffect, useMemo, useState } from 'react';
import { fetchTeacherAcademicProfileStudents, type TeacherAcademicProfileStudent } from '../../services/teacherAcademicProfileDirectoryService';
import { createLearningIntervention, getInterventionIntelligence, updateLearningIntervention, type InterventionIntelligence, type InterventionRecommendation } from '../../services/studentInterventionService';
import './TeacherInterventionIntelligencePage.css';

const labels: Record<string,string>={targeted_question_practice:'Targeted question practice',writing_practice:'Writing Hub practice',reassessment:'Reassess first',teacher_support:'Teacher support',custom:'Custom support'};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';

const TeacherInterventionIntelligencePage:React.FC=()=>{
 const params=useMemo(()=>new URLSearchParams(window.location.search),[]);
 const [students,setStudents]=useState<TeacherAcademicProfileStudent[]>([]); const [studentId,setStudentId]=useState(params.get('student')||''); const [subject,setSubject]=useState(params.get('subject')||'all');
 const [data,setData]=useState<InterventionIntelligence|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [query,setQuery]=useState('');
 const [editing,setEditing]=useState<InterventionRecommendation|null>(null); const [goal,setGoal]=useState(''); const [targetDate,setTargetDate]=useState('');
 const loadStudents=async()=>{try{const list=await fetchTeacherAcademicProfileStudents();setStudents(list);if(!studentId&&list.length)setStudentId(list[0].student_id);}catch(e){setError(e instanceof Error?e.message:'Students could not be loaded.');}finally{setLoading(false);}};
 useEffect(()=>{void loadStudents();},[]);
 useEffect(()=>{if(!studentId)return;setLoading(true);setError(null);void getInterventionIntelligence(studentId,subject==='all'?null:subject).then(setData).catch(e=>setError(e instanceof Error?e.message:'Intervention intelligence could not be loaded.')).finally(()=>setLoading(false));},[studentId,subject]);
 const visible=students.filter(s=>!query.trim()||`${s.student_name} ${s.class_name||''}`.toLowerCase().includes(query.trim().toLowerCase()));
 const selected=students.find(s=>s.student_id===studentId); const subjects=selected?.subjects||[];
 const refresh=async()=>{if(studentId)setData(await getInterventionIntelligence(studentId,subject==='all'?null:subject));};
 const createPlan=async()=>{if(!editing)return;setLoading(true);setError(null);try{await createLearningIntervention({studentId,skillKey:editing.skill_key,interventionType:editing.recommended_type,goal:goal||editing.suggested_goal,targetDate:targetDate||null});setEditing(null);setGoal('');setTargetDate('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not create intervention.');}finally{setLoading(false);}};
 const act=async(id:string,action:'start'|'complete'|'cancel')=>{let outcome: any=undefined,note='';if(action==='complete'){outcome=prompt('Outcome: improved, resolved, no_change, or needs_more_support')||'';if(!['improved','resolved','no_change','needs_more_support'].includes(outcome))return;note=prompt('Optional outcome note')||'';}if(action==='cancel')note=prompt('Reason for cancelling (optional)')||'';setLoading(true);try{await updateLearningIntervention({interventionId:id,action,note,outcomeStatus:outcome});await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not update intervention.');}finally{setLoading(false);}};
 return <main className="intervention-page"><header><div><span>BH</span><div><strong>Intervention Intelligence</strong><small>Evidence-led academic support</small></div></div><button onClick={()=>window.history.length>1?window.history.back():window.location.assign('/teacher-academic-profiles.html')}>Back to profiles</button></header>
 <section className="intervention-hero"><div><span>Phase 7</span><h1>Turn persistent evidence into targeted action</h1><p>Recommendations come from the student’s longitudinal learning memory, evidence recency and content Brain Heist can actually assign. No intervention is generated from one isolated low score.</p></div>{data?<div><strong>{data.recommendations.filter(x=>x.priority==='high').length}</strong><small>high-priority recommendations</small></div>:null}</section>
 {error?<div className="intervention-alert">{error}</div>:null}
 <section className="intervention-controls"><label>Find student<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or class"/></label><label>Student<select value={studentId} onChange={e=>{setStudentId(e.target.value);setSubject('all')}}><option value="">Choose student</option>{visible.map(s=><option key={`${s.student_id}:${s.class_name}`} value={s.student_id}>{s.student_name} · Class {s.class_name||'—'}</option>)}</select></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="all">All authorised subjects</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></label></section>
 {loading&&!data?<div className="intervention-loading">Analysing longitudinal evidence…</div>:null}
 {data?<><section className="intervention-student"><div><span>Student</span><h2>{data.student.name}</h2><p>Grade {data.student.grade||'—'} · Class {data.student.class_name||'—'}</p></div><p>Recommendations explain <strong>why</strong> action is suggested and preserve the baseline state for future outcome review.</p></section>
 <section className="intervention-panel"><div className="intervention-heading"><div><span>Recommended next actions</span><h2>Evidence-led intervention queue</h2></div><p>Stale persistent areas are reassessed before support is prescribed.</p></div><div className="intervention-recommendations">{data.recommendations.map(r=><article key={r.skill_key} className={`priority-${r.priority}`}><div className="intervention-card-top"><span>{r.subject}{r.topic?` · ${r.topic}`:''}</span><b>{r.priority}</b></div><h3>{r.skill}</h3><p>{r.rationale}</p><dl><div><dt>Current state</dt><dd>{r.status.replaceAll('_',' ')}</dd></div><div><dt>Evidence</dt><dd>{r.evidence_items} items</dd></div><div><dt>Latest</dt><dd>{fmt(r.last_observed_at)}</dd></div><div><dt>Questions available</dt><dd>{r.available_questions}</dd></div></dl><div className="intervention-action"><span>{labels[r.recommended_type]}</span>{r.has_open_intervention?<strong>Plan already open</strong>:<button onClick={()=>{setEditing(r);setGoal(r.suggested_goal)}}>Create intervention</button>}</div></article>)}{!data.recommendations.length?<div className="intervention-empty">No unresolved focus areas are currently available in this scope.</div>:null}</div></section>
 <section className="intervention-panel"><div className="intervention-heading"><div><span>Support history</span><h2>Intervention plans</h2></div></div><div className="intervention-plans">{data.interventions.map(i=><article key={i.id}><div><span>{i.subject}</span><b>{i.status}</b></div><h3>{i.skill}</h3><p>{i.goal}</p><small>Baseline: {i.baseline_status.replaceAll('_',' ')} · {i.baseline_evidence_items} evidence items · created {fmt(i.created_at)}</small>{i.outcome_status?<strong>Outcome: {i.outcome_status.replaceAll('_',' ')}</strong>:null}<div>{i.status==='planned'?<button onClick={()=>void act(i.id,'start')}>Start plan</button>:null}{i.status==='active'?<button onClick={()=>void act(i.id,'complete')}>Complete & record outcome</button>:null}{['planned','active'].includes(i.status)?<button className="secondary" onClick={()=>void act(i.id,'cancel')}>Cancel</button>:null}</div></article>)}{!data.interventions.length?<div className="intervention-empty">No intervention plans have been created for this student yet.</div>:null}</div></section></>:null}
 {editing?<div className="intervention-modal-layer"><button className="backdrop" onClick={()=>setEditing(null)} aria-label="Close"/><section className="intervention-modal"><span>{labels[editing.recommended_type]}</span><h2>{editing.skill}</h2><p>{editing.rationale}</p><label>Goal<textarea value={goal} onChange={e=>setGoal(e.target.value)} /></label><label>Target review date<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)} /></label><small>Baseline will be locked at {editing.status.replaceAll('_',' ')} with {editing.evidence_items} qualifying evidence items.</small><div><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button onClick={()=>void createPlan()}>Create intervention plan</button></div></section></div>:null}
 </main>;
};
export default TeacherInterventionIntelligencePage;
