-- Recalculate ALL AS Chemistry test scores using centralized master answer key.
WITH quiz_question_key AS (
  SELECT * FROM (VALUES
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 1, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 2, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 3, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 4, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 6, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 7, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 8, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 10, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 11, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 12, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 13, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 14, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 15, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 16, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 1)', 17, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 18, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 19, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 20, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 21, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 22, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 23, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 24, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 25, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 26, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 27, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 28, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 29, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 30, 'B'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 31, 'C'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 32, 'D'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 33, 'A'),
    ('AS Chemistry Ch21 ( Analytical techniques ) (Part 2)', 34, 'B'),
    ('AS Chemistry — Atomic Structure (Part 1)', 1, 'A'),
    ('AS Chemistry — Atomic Structure (Part 1)', 2, 'C'),
    ('AS Chemistry — Atomic Structure (Part 1)', 3, 'C'),
    ('AS Chemistry — Atomic Structure (Part 1)', 4, 'D'),
    ('AS Chemistry — Atomic Structure (Part 1)', 5, 'B'),
    ('AS Chemistry — Atomic Structure (Part 1)', 6, 'B'),
    ('AS Chemistry — Atomic Structure (Part 1)', 7, 'A'),
    ('AS Chemistry — Atomic Structure (Part 1)', 8, 'A'),
    ('AS Chemistry — Atomic Structure (Part 1)', 9, 'D'),
    ('AS Chemistry — Atomic Structure (Part 1)', 10, 'D'),
    ('AS Chemistry — Atomic Structure (Part 1)', 11, 'B'),
    ('AS Chemistry — Atomic Structure (Part 1)', 12, 'A'),
    ('AS Chemistry — Atomic Structure (Part 1)', 13, 'C'),
    ('AS Chemistry — Atomic Structure (Part 1)', 14, 'A'),
    ('AS Chemistry — Atomic Structure (Part 1)', 15, 'C'),
    ('AS Chemistry — Atomic Structure (Part 1)', 16, 'A'),
    ('AS Chemistry — Atomic Structure (Part 1)', 17, 'D'),
    ('AS Chemistry — Atomic Structure (Part 1)', 18, 'C'),
    ('AS Chemistry — Atomic Structure (Part 1)', 19, 'C'),
    ('AS Chemistry — Atomic Structure (Part 1)', 20, 'B'),
    ('AS Chemistry — Atomic Structure (Part 1)', 21, 'B'),
    ('AS Chemistry — Atomic Structure (Part 1)', 22, 'A'),
    ('AS Chemistry — Atomic Structure (Part 1)', 23, 'B'),
    ('AS Chemistry — Atomic Structure (Part 1)', 24, 'D'),
    ('AS Chemistry — Atomic Structure (Part 1)', 25, 'A'),
    ('AS Chemistry — Atomic Structure (Part 2)', 26, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 27, 'D'),
    ('AS Chemistry — Atomic Structure (Part 2)', 28, 'A'),
    ('AS Chemistry — Atomic Structure (Part 2)', 29, 'D'),
    ('AS Chemistry — Atomic Structure (Part 2)', 30, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 31, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 32, 'A'),
    ('AS Chemistry — Atomic Structure (Part 2)', 33, 'D'),
    ('AS Chemistry — Atomic Structure (Part 2)', 34, 'B'),
    ('AS Chemistry — Atomic Structure (Part 2)', 35, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 36, 'D'),
    ('AS Chemistry — Atomic Structure (Part 2)', 37, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 38, 'B'),
    ('AS Chemistry — Atomic Structure (Part 2)', 39, 'A'),
    ('AS Chemistry — Atomic Structure (Part 2)', 40, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 41, 'D'),
    ('AS Chemistry — Atomic Structure (Part 2)', 42, 'A'),
    ('AS Chemistry — Atomic Structure (Part 2)', 43, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 44, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 45, 'D'),
    ('AS Chemistry — Atomic Structure (Part 2)', 46, 'C'),
    ('AS Chemistry — Atomic Structure (Part 2)', 47, 'A'),
    ('AS Chemistry — Atomic Structure (Part 2)', 48, 'D'),
    ('AS Chemistry — Atomic Structure (Part 2)', 49, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 2, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 3, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 4, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 5, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 6, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 7, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 8, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 9, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 11, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 12, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 13, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 14, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 15, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 16, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 17, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 18, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 20, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 22, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 23, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 24, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 25, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 26, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 27, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 28, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 29, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 30, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 1)', 31, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 32, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 33, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 34, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 35, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 36, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 37, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 38, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 39, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 40, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 41, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 42, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 43, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 44, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 45, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 47, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 48, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 49, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 51, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 52, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 53, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 54, 'D'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 55, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 56, 'A'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 57, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 58, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 59, 'B'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 60, 'C'),
    ('AS Chemistry Ch2 (Atoms, molecules and stoichiometry) (Part 2)', 64, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 1, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 2, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 3, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 4, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 5, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 6, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 7, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 8, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 11, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 12, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 13, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 14, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 15, 'C'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 16, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 17, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 18, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 19, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 20, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 22, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 23, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 24, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 25, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 26, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 27, 'C'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 28, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 29, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 30, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 31, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 1)', 32, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 33, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 34, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 35, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 36, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 37, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 38, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 39, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 40, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 41, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 42, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 43, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 44, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 45, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 47, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 48, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 49, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 51, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 52, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 53, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 54, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 55, 'C'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 56, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 57, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 58, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 59, 'D'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 60, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 61, 'A'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 62, 'B'),
    ('AS Chemistry Ch17 ( Carbonyl compounds ) (Part 2)', 63, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 2, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 3, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 4, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 5, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 6, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 7, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 8, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 11, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 12, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 13, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 14, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 15, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 16, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 17, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 18, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 19, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 20, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 22, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 23, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 24, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 25, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 26, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 27, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 28, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 29, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 30, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 31, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 32, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 33, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 34, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 35, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 36, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 37, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 38, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 39, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 40, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 1)', 41, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 42, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 43, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 44, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 45, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 46, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 47, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 48, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 49, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 50, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 51, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 52, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 53, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 54, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 55, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 56, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 57, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 58, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 59, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 60, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 61, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 62, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 63, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 64, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 65, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 66, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 67, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 68, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 69, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 70, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 71, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 72, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 73, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 74, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 75, 'A'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 76, 'C'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 77, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 78, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 79, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 80, 'D'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 81, 'B'),
    ('AS Chemistry Ch18 ( Carboxylic acids and derivatives ) (Part 2)', 82, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 1, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 2, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 3, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 4, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 5, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 6, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 7, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 8, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 10, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 11, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 13, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 14, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 15, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 16, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 17, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 18, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 20, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 21, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 22, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 23, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 24, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 25, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 26, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 27, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 1)', 28, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 29, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 30, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 31, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 32, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 33, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 34, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 35, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 36, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 37, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 38, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 39, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 40, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 41, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 42, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 43, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 44, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 45, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 46, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 47, 'C'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 48, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 49, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 51, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 52, 'A'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 53, 'B'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 54, 'D'),
    ('AS Chemistry Ch3 (Chemical bonding) (Part 2)', 55, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 1, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 2, 'A'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 3, 'A'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 4, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 6, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 7, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 8, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 9, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 10, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 11, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 12, 'A'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 13, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 14, 'A'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 15, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 16, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 17, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 18, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 20, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 22, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 23, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 24, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 25, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 26, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 1)', 27, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 28, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 29, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 30, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 31, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 32, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 33, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 34, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 35, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 36, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 37, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 38, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 39, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 40, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 41, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 42, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 43, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 44, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 45, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 47, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 48, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 49, 'C'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 51, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 52, 'B'),
    ('AS Chemistry Ch5 (Chemical Energetics) (Part 2)', 53, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 2, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 3, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 4, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 6, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 7, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 8, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 9, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 11, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 12, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 13, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 14, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 15, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 16, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 17, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 18, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 20, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 21, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 22, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 23, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 24, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 25, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 26, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 27, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 28, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 29, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 30, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 31, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 32, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 33, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 34, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 35, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 36, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 37, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 38, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 39, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 40, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 41, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 42, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 1)', 43, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 44, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 45, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 47, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 48, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 49, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 51, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 52, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 53, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 54, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 55, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 56, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 57, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 58, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 59, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 60, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 61, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 62, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 63, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 64, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 65, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 66, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 67, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 68, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 69, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 70, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 71, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 72, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 73, 'A'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 74, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 75, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 76, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 77, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 78, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 79, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 80, 'B'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 81, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 82, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 83, 'C'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 84, 'D'),
    ('AS Chemistry Ch9 (Chemical Periodicity) (Part 2)', 85, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 1, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 2, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 3, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 4, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 5, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 6, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 7, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 8, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 9, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 10, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 11, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 13, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 14, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 15, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 16, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 17, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 18, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 19, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 20, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 21, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 22, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 23, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 24, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 25, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 26, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 27, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 1)', 28, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 29, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 30, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 31, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 32, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 33, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 34, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 35, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 36, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 37, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 38, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 39, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 40, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 41, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 42, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 43, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 44, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 45, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 46, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 47, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 48, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 49, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 50, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 51, 'B'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 52, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 53, 'C'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 54, 'D'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 55, 'A'),
    ('AS Chemistry Ch6 (Electrochemistry) (Part 2)', 56, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 1, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 2, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 3, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 4, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 5, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 6, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 7, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 8, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 10, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 11, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 13, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 14, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 15, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 16, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 17, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 18, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 19, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 20, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 22, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 23, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 24, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 25, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 26, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 27, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 28, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 29, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 30, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 31, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 32, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 33, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 34, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 35, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 36, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 1)', 37, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 38, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 39, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 40, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 41, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 42, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 43, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 44, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 45, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 47, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 48, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 49, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 51, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 52, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 53, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 54, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 55, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 56, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 57, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 58, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 59, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 60, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 61, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 62, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 63, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 64, 'C'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 65, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 66, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 67, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 68, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 69, 'D'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 70, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 71, 'B'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 72, 'A'),
    ('AS Chemistry Ch7 (Equilibria) (Part 2)', 73, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 2, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 3, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 4, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 6, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 7, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 8, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 10, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 11, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 13, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 14, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 15, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 16, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 17, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 18, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 20, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 21, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 22, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 23, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 24, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 25, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 26, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 27, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 28, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 29, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 30, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 31, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 32, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 33, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 34, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 35, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 36, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 37, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 38, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 39, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 40, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 1)', 41, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 42, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 43, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 44, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 45, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 47, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 48, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 49, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 50, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 51, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 52, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 53, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 54, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 55, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 56, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 57, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 58, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 59, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 60, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 61, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 62, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 63, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 64, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 65, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 66, 'B'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 67, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 68, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 69, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 70, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 71, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 72, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 73, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 74, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 75, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 76, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 77, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 78, 'D'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 79, 'A'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 80, 'C'),
    ('AS Chemistry Ch11 ( Group 17 ) (Part 2)', 81, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 1, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 2, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 3, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 4, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 6, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 7, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 8, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 9, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 11, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 13, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 14, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 15, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 16, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 17, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 18, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 19, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 20, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 22, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 23, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 24, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 25, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 26, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 27, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 28, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 29, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 30, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 31, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 32, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 33, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 34, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 35, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 36, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 1)', 37, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 38, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 39, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 40, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 41, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 42, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 43, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 44, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 45, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 46, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 47, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 48, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 49, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 50, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 51, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 52, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 53, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 54, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 55, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 56, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 57, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 58, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 59, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 60, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 61, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 62, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 63, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 64, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 65, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 66, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 67, 'D'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 68, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 69, 'C'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 70, 'B'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 71, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 72, 'A'),
    ('AS Chemistry Ch10 (Group 2) (Part 2)', 73, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 1, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 2, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 3, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 4, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 6, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 7, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 8, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 9, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 10, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 11, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 12, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 13, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 14, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 15, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 16, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 17, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 18, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 20, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 22, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 23, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 24, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 25, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 26, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 27, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 1)', 28, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 29, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 30, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 31, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 32, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 33, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 34, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 35, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 36, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 37, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 38, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 39, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 40, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 41, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 42, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 43, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 44, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 45, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 46, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 47, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 48, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 49, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 50, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 51, 'D'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 52, 'B'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 53, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 54, 'A'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 55, 'C'),
    ('AS Chemistry Ch15 ( Halogen compounds ) (Part 2)', 56, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 2, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 3, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 4, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 6, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 7, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 8, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 9, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 11, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 12, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 13, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 14, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 15, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 16, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 17, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 18, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 19, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 20, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 21, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 22, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 23, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 24, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 25, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 26, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 27, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 28, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 29, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 1)', 30, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 31, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 32, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 33, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 34, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 35, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 36, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 37, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 38, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 39, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 40, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 41, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 42, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 43, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 44, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 45, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 46, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 47, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 48, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 49, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 51, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 52, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 53, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 54, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 55, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 56, 'B'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 57, 'D'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 58, 'C'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 59, 'A'),
    ('AS Chemistry Ch14 ( Hydrocarbons ) (Part 2)', 60, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 1, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 2, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 3, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 4, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 6, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 7, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 8, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 10, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 11, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 12, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 13, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 14, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 15, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 16, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 17, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 18, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 20, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 22, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 23, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 24, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 25, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 26, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 27, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 28, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 29, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 30, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 31, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 32, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 33, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 34, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 35, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 36, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 37, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 38, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 39, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 40, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 41, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 42, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 43, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 1)', 44, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 45, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 47, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 48, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 49, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 51, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 52, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 53, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 54, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 55, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 56, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 57, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 58, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 59, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 60, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 61, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 62, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 63, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 64, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 65, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 66, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 67, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 68, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 69, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 70, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 71, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 72, 'D'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 73, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 74, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 75, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 76, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 77, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 78, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 79, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 80, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 81, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 82, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 83, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 84, 'A'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 85, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 86, 'B'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 87, 'C'),
    ('AS Chemistry Ch16 ( Hydroxy compounds ) (Part 2)', 88, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 2, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 3, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 4, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 6, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 7, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 8, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 11, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 13, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 14, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 15, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 16, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 17, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 18, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 19, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 20, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 21, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 22, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 23, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 24, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 25, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 26, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 27, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 28, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 29, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 30, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 31, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 32, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 33, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 34, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 35, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 36, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 37, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 1)', 38, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 39, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 40, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 41, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 42, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 43, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 44, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 45, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 46, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 47, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 48, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 49, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 50, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 51, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 52, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 53, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 54, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 55, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 56, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 57, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 58, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 59, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 60, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 61, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 62, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 63, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 64, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 65, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 66, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 67, 'D'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 68, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 69, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 70, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 71, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 72, 'A'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 73, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 74, 'C'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 75, 'B'),
    ('AS Chemistry Ch13 ( An introduction to AS Level organic chemistry ) (Part 2)', 76, 'B'),
    ('AS Chemistry Ch19 ( Nitrogen compounds ) (Part 1)', 1, 'D'),
    ('AS Chemistry Ch19 ( Nitrogen compounds ) (Part 1)', 2, 'C'),
    ('AS Chemistry Ch19 ( Nitrogen compounds ) (Part 1)', 3, 'C'),
    ('AS Chemistry Ch19 ( Nitrogen compounds ) (Part 2)', 4, 'A'),
    ('AS Chemistry Ch19 ( Nitrogen compounds ) (Part 2)', 5, 'D'),
    ('AS Chemistry Ch19 ( Nitrogen compounds ) (Part 2)', 6, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 2, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 3, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 4, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 5, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 6, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 7, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 8, 'A'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 9, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 11, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 12, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 13, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 14, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 15, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 16, 'A'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 17, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 18, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 19, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 20, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 21, 'A'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 22, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 23, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 24, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 1)', 25, 'A'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 26, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 27, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 28, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 29, 'A'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 30, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 31, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 32, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 33, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 34, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 35, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 36, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 37, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 38, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 39, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 40, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 41, 'A'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 42, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 43, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 44, 'C'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 45, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 47, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 48, 'A'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 49, 'D'),
    ('AS Chemistry Ch12 ( Nitrogen and sulfur ) (Part 2)', 50, 'C'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 1, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 2, 'A'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 3, 'D'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 4, 'A'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 5, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 6, 'D'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 7, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 1)', 8, 'D'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 9, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 10, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 11, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 12, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 13, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 14, 'A'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 15, 'B'),
    ('AS Chemistry Ch20 ( Polymerisation) (Part 2)', 16, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 1, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 2, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 3, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 4, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 5, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 6, 'A'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 7, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 8, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 9, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 11, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 13, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 14, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 15, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 16, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 17, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 18, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 19, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 20, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 1)', 21, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 22, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 23, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 24, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 25, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 26, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 27, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 28, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 29, 'B'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 30, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 31, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 32, 'A'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 33, 'A'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 34, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 35, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 36, 'A'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 37, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 38, 'C'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 39, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 40, 'D'),
    ('AS Chemistry Ch8 (Reaction kinetics) (Part 2)', 41, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 1, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 2, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 3, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 4, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 5, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 6, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 7, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 8, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 9, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 10, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 11, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 12, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 13, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 14, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 15, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 16, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 17, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 18, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 19, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 20, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 21, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 22, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 23, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 24, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 25, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 26, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 27, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 28, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 29, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 30, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 1)', 31, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 32, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 33, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 34, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 35, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 36, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 37, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 38, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 39, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 40, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 41, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 42, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 43, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 44, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 45, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 46, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 47, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 48, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 49, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 50, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 51, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 52, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 53, 'B'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 54, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 55, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 56, 'A'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 57, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 58, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 59, 'D'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 60, 'C'),
    ('AS Chemistry Ch4 (States of matter) (Part 2)', 61, 'D')
  ) AS t(quiz_name, question_number, correct_answer)
),
part_totals AS (
  SELECT quiz_name, COUNT(*)::int AS total_questions
  FROM quiz_question_key
  GROUP BY quiz_name
),
recalc AS (
  SELECT qs.id, qs.quiz_name, pt.total_questions,
         COUNT(*) FILTER (WHERE UPPER(TRIM(COALESCE(resp.value, ''))) = qqk.correct_answer)::int AS new_score
  FROM quiz_scores qs
  JOIN quiz_question_key qqk ON qqk.quiz_name = qs.quiz_name
  JOIN part_totals pt ON pt.quiz_name = qs.quiz_name
  LEFT JOIN LATERAL (
    SELECT value
    FROM jsonb_each_text(COALESCE(qs.answers->'responses', '{}'::jsonb))
    WHERE key = qqk.question_number::text
  ) resp ON TRUE
  WHERE qs.quiz_name LIKE 'AS Chemistry%'
  GROUP BY qs.id, qs.quiz_name, pt.total_questions
)
UPDATE quiz_scores qs
SET score = recalc.new_score,
    total_questions = recalc.total_questions,
    percentage = ROUND((recalc.new_score::numeric * 100.0) / NULLIF(recalc.total_questions, 0))::int
FROM recalc
WHERE qs.id = recalc.id;
