import type { Language } from '../../src/i18n/language';

export const PORTAL_COPY = {
  en: {
    tagline: 'Learn · Compete · Grow',
    heroLine1: 'Where school', heroLine2: 'feels like a', heroLine3: 'game.',
    heroBody: 'One identity. One learning world. Sign in instantly or explore what Brains Heist can do.',
    notHere: 'Not here to sign in?', explore: 'Explore Brains Heist',
    categories: 'Schools · Learning · IELTS · Admissions · Competition',
    access: 'Brains Heist access', welcome: 'Welcome back, Agent.', createIdentity: 'Create your identity.', resetAccess: 'Reset access.',
    fastest: 'The fastest way in is Google.', googleNew: 'Google works for new accounts too.', resetHint: 'We’ll send you a secure reset link.',
    google: 'Continue with Google', connecting: 'Connecting…', or: 'or', backSignIn: 'Back to sign in',
    username: 'Choose a username', email: 'Email address', password: 'Password', forgot: 'Forgot password?',
    enter: 'Enter →', createAccount: 'Create account →', sendReset: 'Send reset link →', working: 'Working…',
    newHere: 'New to Brains Heist?', already: 'Already have an account?', signIn: 'Sign in', createAccountPlain: 'Create account',
    identityVerification: 'Identity verification', confirmEmail: 'Confirm your email', sentConfirmation: 'We sent a confirmation to',
    confirmationCode: 'Confirmation code', confirmWithin: 'Confirm within seven days.', pendingExpires: 'Pending account expires {date}.',
    confirming: 'Confirming…', confirmContinue: 'Confirm and continue', sending: 'Sending…', resend: 'Resend confirmation', changeEmail: 'Change email',
    universe: 'The Brains Heist Universe', missions: 'One system. Different missions.', universeBody: 'Explore each part of Brains Heist and see exactly what it is designed to do.',
    backPortal: 'Back to portal', requestDemo: 'Request a school demo', discover: 'Discover →', alreadyPart: 'Already part of Brains Heist?', returnSignIn: 'Return to sign in →',
    learnEyebrow: 'LEARN', learnTitle: 'Learning', learnCopy: 'Classes, assignments, progress and a learning loop students can actually feel.',
    competeEyebrow: 'COMPETE', competeTitle: 'Competition', competeCopy: 'XP, clans, rankings, battles and momentum built into the school day.',
    prepareEyebrow: 'PREPARE', ieltsTitle: 'IELTS', ieltsCopy: 'Diagnostics, targeted practice and a clear path from current level to target band.',
    operateEyebrow: 'OPERATE', schoolsTitle: 'Schools', schoolsCopy: 'Classes, teachers, reporting, admissions and school-wide visibility in one system.',
    discoverEyebrow: 'DISCOVER', admissionsTitle: 'Admissions', admissionsCopy: 'Candidate testing, placement intelligence and school-ready admissions workflows.',
    legal: 'Legal', terms: 'Terms of Service', privacy: 'Privacy Policy', refund: 'Refund Policy', resources: 'Resources', pricing: 'Pricing', contact: 'Contact Us', ieltsPrep: 'IELTS Prep', requestDemoShort: 'Request demo', getInTouch: 'Get in touch', rights: 'All rights reserved.', payments: 'Payments secured by Paddle — Merchant of Record',
    footerBody: 'Gamified English & Maths learning for schools — assessments, live competition and meaningful progress insights.'
  },
  ar: {
    tagline: 'تعلّم · تنافس · تطوّر',
    heroLine1: 'حيث تصبح المدرسة', heroLine2: 'تجربة تشبه', heroLine3: 'اللعبة.',
    heroBody: 'هوية واحدة. عالم تعلّم واحد. سجّل الدخول فوراً أو استكشف ما يمكن لـ Brains Heist أن يقدمه.',
    notHere: 'لست هنا لتسجيل الدخول؟', explore: 'استكشف Brains Heist',
    categories: 'المدارس · التعلّم · IELTS · القبول · المنافسة',
    access: 'الدخول إلى Brains Heist', welcome: 'مرحباً بعودتك، أيها العميل.', createIdentity: 'أنشئ هويتك.', resetAccess: 'استعد الوصول إلى حسابك.',
    fastest: 'أسرع طريقة للدخول هي عبر Google.', googleNew: 'يمكنك أيضاً إنشاء حساب جديد باستخدام Google.', resetHint: 'سنرسل لك رابطاً آمناً لإعادة تعيين كلمة المرور.',
    google: 'المتابعة باستخدام Google', connecting: 'جارٍ الاتصال…', or: 'أو', backSignIn: 'العودة إلى تسجيل الدخول',
    username: 'اختر اسم مستخدم', email: 'البريد الإلكتروني', password: 'كلمة المرور', forgot: 'هل نسيت كلمة المرور؟',
    enter: 'دخول ←', createAccount: 'إنشاء حساب ←', sendReset: 'إرسال رابط إعادة التعيين ←', working: 'جارٍ التنفيذ…',
    newHere: 'جديد في Brains Heist؟', already: 'لديك حساب بالفعل؟', signIn: 'تسجيل الدخول', createAccountPlain: 'إنشاء حساب',
    identityVerification: 'التحقق من الهوية', confirmEmail: 'أكد بريدك الإلكتروني', sentConfirmation: 'أرسلنا رسالة تأكيد إلى',
    confirmationCode: 'رمز التأكيد', confirmWithin: 'أكّد الحساب خلال سبعة أيام.', pendingExpires: 'تنتهي مهلة الحساب المعلّق في {date}.',
    confirming: 'جارٍ التأكيد…', confirmContinue: 'تأكيد ومتابعة', sending: 'جارٍ الإرسال…', resend: 'إعادة إرسال التأكيد', changeEmail: 'تغيير البريد الإلكتروني',
    universe: 'عالم Brains Heist', missions: 'نظام واحد. مهام مختلفة.', universeBody: 'استكشف كل جزء من Brains Heist واعرف بالضبط ما صُمم من أجله.',
    backPortal: 'العودة إلى البوابة', requestDemo: 'طلب عرض توضيحي للمدرسة', discover: 'استكشف ←', alreadyPart: 'هل أنت بالفعل ضمن Brains Heist؟', returnSignIn: 'العودة إلى تسجيل الدخول ←',
    learnEyebrow: 'تعلّم', learnTitle: 'التعلّم', learnCopy: 'فصول وواجبات وتقدّم ودورة تعلّم يستطيع الطلاب ملاحظة أثرها فعلياً.',
    competeEyebrow: 'تنافس', competeTitle: 'المنافسة', competeCopy: 'نقاط XP وعشائر وتصنيفات ومواجهات وزخم تنافسي مدمج في اليوم الدراسي.',
    prepareEyebrow: 'استعد', ieltsTitle: 'IELTS', ieltsCopy: 'تشخيص للمستوى، وتدريب موجّه، ومسار واضح من مستواك الحالي إلى الدرجة المستهدفة.',
    operateEyebrow: 'أدِر', schoolsTitle: 'المدارس', schoolsCopy: 'الفصول والمعلمون والتقارير والقبول ورؤية شاملة للمدرسة داخل نظام واحد.',
    discoverEyebrow: 'اكتشف', admissionsTitle: 'القبول', admissionsCopy: 'اختبارات للمتقدمين، وذكاء لتحديد المستوى، وسير عمل متكامل لعمليات القبول المدرسي.',
    legal: 'قانوني', terms: 'شروط الخدمة', privacy: 'سياسة الخصوصية', refund: 'سياسة الاسترداد', resources: 'الموارد', pricing: 'الأسعار', contact: 'تواصل معنا', ieltsPrep: 'التحضير لـ IELTS', requestDemoShort: 'طلب عرض توضيحي', getInTouch: 'تواصل معنا', rights: 'جميع الحقوق محفوظة.', payments: 'المدفوعات مؤمّنة عبر Paddle — التاجر المسجّل',
    footerBody: 'تعلّم تفاعلي للغة الإنجليزية والرياضيات للمدارس — تقييمات ومنافسات مباشرة ورؤى مفيدة حول التقدّم.'
  },
  ru: {
    tagline: 'Учись · Соревнуйся · Развивайся',
    heroLine1: 'Школа,', heroLine2: 'которая ощущается как', heroLine3: 'игра.',
    heroBody: 'Одна учётная запись. Один учебный мир. Войдите сразу или узнайте, что умеет Brains Heist.',
    notHere: 'Вы здесь не для входа?', explore: 'Исследовать Brains Heist',
    categories: 'Школы · Обучение · IELTS · Поступление · Соревнование',
    access: 'Доступ к Brains Heist', welcome: 'С возвращением, агент.', createIdentity: 'Создайте свою учётную запись.', resetAccess: 'Восстановление доступа.',
    fastest: 'Самый быстрый вход — через Google.', googleNew: 'Через Google можно также создать новый аккаунт.', resetHint: 'Мы отправим безопасную ссылку для сброса пароля.',
    google: 'Продолжить с Google', connecting: 'Подключение…', or: 'или', backSignIn: 'Назад ко входу',
    username: 'Выберите имя пользователя', email: 'Электронная почта', password: 'Пароль', forgot: 'Забыли пароль?',
    enter: 'Войти →', createAccount: 'Создать аккаунт →', sendReset: 'Отправить ссылку →', working: 'Выполняется…',
    newHere: 'Впервые в Brains Heist?', already: 'Уже есть аккаунт?', signIn: 'Войти', createAccountPlain: 'Создать аккаунт',
    identityVerification: 'Проверка учётной записи', confirmEmail: 'Подтвердите электронную почту', sentConfirmation: 'Мы отправили подтверждение на',
    confirmationCode: 'Код подтверждения', confirmWithin: 'Подтвердите аккаунт в течение семи дней.', pendingExpires: 'Срок ожидания подтверждения: до {date}.',
    confirming: 'Подтверждение…', confirmContinue: 'Подтвердить и продолжить', sending: 'Отправка…', resend: 'Отправить подтверждение снова', changeEmail: 'Изменить почту',
    universe: 'Вселенная Brains Heist', missions: 'Одна система. Разные задачи.', universeBody: 'Исследуйте каждую часть Brains Heist и узнайте, для чего именно она создана.',
    backPortal: 'Назад к входу', requestDemo: 'Запросить демо для школы', discover: 'Подробнее →', alreadyPart: 'Уже используете Brains Heist?', returnSignIn: 'Вернуться ко входу →',
    learnEyebrow: 'УЧИСЬ', learnTitle: 'Обучение', learnCopy: 'Классы, задания, прогресс и учебный цикл, результат которого ученики действительно ощущают.',
    competeEyebrow: 'СОРЕВНУЙСЯ', competeTitle: 'Соревнование', competeCopy: 'XP, кланы, рейтинги, битвы и соревновательная динамика прямо в школьном дне.',
    prepareEyebrow: 'ГОТОВЬСЯ', ieltsTitle: 'IELTS', ieltsCopy: 'Диагностика, целевая практика и понятный путь от текущего уровня к целевому баллу.',
    operateEyebrow: 'УПРАВЛЯЙ', schoolsTitle: 'Школы', schoolsCopy: 'Классы, учителя, отчёты, поступление и единая картина по школе в одной системе.',
    discoverEyebrow: 'ОТКРЫВАЙ', admissionsTitle: 'Поступление', admissionsCopy: 'Тестирование кандидатов, аналитика для определения уровня и рабочие процессы приёма в школу.',
    legal: 'Документы', terms: 'Условия использования', privacy: 'Политика конфиденциальности', refund: 'Политика возврата', resources: 'Ресурсы', pricing: 'Цены', contact: 'Связаться с нами', ieltsPrep: 'Подготовка к IELTS', requestDemoShort: 'Запросить демо', getInTouch: 'Контакты', rights: 'Все права защищены.', payments: 'Платежи защищены Paddle — Merchant of Record',
    footerBody: 'Игровое обучение английскому и математике для школ — оценивание, живые соревнования и полезная аналитика прогресса.'
  }
} as const satisfies Record<Language, Record<string, string>>;

export type PortalCopy = typeof PORTAL_COPY.en;
