import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const student='b30e9c28-96f1-4d34-83e9-9b28b4926f42',teacher='54d6f8f8-8bb2-41e0-83a7-1afac5a21882';
const school='8eeecf5d-0496-4e0d-b5cd-538f91c9cfa0',source='00000000-0000-0000-0000-000000000101',outsider='00000000-0000-0000-0000-000000000102';
const request='00000000-0000-0000-0000-000000000103';let id;
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema private;create schema auth;create schema storage;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table users(id uuid primary key,username text,is_banned boolean default false);
create table ielts_exam_attempts(id uuid primary key,status text);
create table schools(id uuid primary key);create table school_members(school_id uuid,user_id uuid,status text);
create table academic_skill_registry_versions(id uuid primary key,status text);
create table academic_skill_registry_nodes(id uuid primary key,registry_version_id uuid,node_type text,status text);
create table private.ielts_diagnostic_attempt_evidence(attempt_id uuid primary key,student_id uuid,school_id uuid);
create table private.ielts_diagnostic_scoring_runs(attempt_id uuid,server_verified boolean);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(bucket_id text,name text);alter table storage.objects enable row level security;
create function private.ielts_speaking_student_eligible(uuid) returns boolean language sql as $$select $1='${student}'::uuid$$;
create function public.can_manage_ielts_practice_school(uuid) returns boolean language sql as $$select $1='${school}'::uuid and auth.uid()='${teacher}'::uuid$$;
insert into users(id,username) values('${student}','Pilot'),('${teacher}','Teacher'),('${outsider}','Outsider');
insert into ielts_exam_attempts values('${source}','submitted');
insert into schools values('${school}');insert into school_members values('${school}','${student}','active');
insert into academic_skill_registry_versions values('d4ad52b6-fd0f-4068-9982-28b89ff389c5','published');
insert into academic_skill_registry_nodes select unnest(array['0dbe1c8f-403a-493f-afd3-c219310fb18a','d5b1fddb-ba6f-4be1-8513-bb26d822357a','d0aa0bad-ecfa-4598-8f2f-07e93d3fa59b','f9064b63-e3f1-4bfa-8e8e-97a02756afb2']::uuid[]),'d4ad52b6-fd0f-4068-9982-28b89ff389c5','subskill','active';
insert into private.ielts_diagnostic_attempt_evidence values('${source}','${student}','${school}');
insert into private.ielts_diagnostic_scoring_runs values('${source}',true);`);
await db.exec(readFileSync('supabase/migrations/20261008195545_ielts_targeted_listening_pilot.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/20261008201324_ielts_learning_exposure_integrity.sql','utf8'));
const actor=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const detail=async()=> (await db.query('select rpc_ielts_learning_detail($1) d',[id])).rows[0].d;
const allocate=()=>db.query('select rpc_ielts_learning_allocate($1,$2,$3,$4,$5,null,$6) id',[school,student,'bh-ielts-targeted-listening-l1-v1',source,'Synthetic delivery test; no diagnosis asserted.',request]);
test('allocation is authorized, source-linked, pilot-only and retry-safe',async()=>{
 await actor(outsider);await assert.rejects(allocate(),/not_authorized/);
 await actor(teacher);id=(await allocate()).rows[0].id;assert.equal((await allocate()).rows[0].id,id);
 await assert.rejects(db.query('select rpc_ielts_learning_allocate($1,$2,$3,$4,$5,null,$6)',[school,student,'bh-ielts-targeted-listening-l1-v1',source,'Different request payload',request]),/request_conflict/);
 await actor(student);const d=await detail();assert.equal(d.questions.length,6);assert.equal(d.result,null);
 assert.equal(JSON.stringify(d.questions).includes('accepted_answers'),false);
 await actor(outsider);await assert.rejects(detail(),/not_authorized/);
});
test('revision-checked saves preserve concurrent edits and reject invalid/foreign payloads',async()=>{
 await actor(student);const first=(await db.query('select rpc_ielts_learning_save($1,0,$2) r',[id,JSON.stringify({q1:'Sunday'})])).rows[0].r;assert.equal(first,1);
 assert.equal((await db.query('select rpc_ielts_learning_save($1,0,$2) r',[id,JSON.stringify({q1:'Sunday'})])).rows[0].r,1);
 await assert.rejects(db.query('select rpc_ielts_learning_save($1,0,$2)',[id,JSON.stringify({q1:'Monday'})]),/draft_changed/);
 await assert.rejects(db.query('select rpc_ielts_learning_save($1,1,$2)',[id,JSON.stringify({estimated_band:'9'})]),/invalid_answers/);
 await actor(teacher);await assert.rejects(db.query('select rpc_ielts_learning_save($1,1,$2)',[id,'{}']),/task_not_active/);
});
test('server marks exact keys, qualifiers, word limits and unanswered work; submission cannot duplicate or mutate',async()=>{
 await actor(student);const answers={q1:'  sUnDaY ',q2:'ten',q3:'twenty',q4:'twelve',q5:'a notebook please'};
 await db.query('select rpc_ielts_learning_save($1,1,$2)',[id,JSON.stringify(answers)]);
 const first=(await db.query('select rpc_ielts_learning_submit($1,2) d',[id])).rows[0].d;
 assert.equal(first.result.score,3);assert.equal(first.result.outcomes[5].response_state,'unanswered');
 const second=(await db.query('select rpc_ielts_learning_submit($1,0) d',[id])).rows[0].d;assert.deepEqual(first.result,second.result);
 assert.equal((await db.query('select count(*)::int n from private.ielts_learning_submissions')).rows[0].n,1);
 await assert.rejects(db.query('select rpc_ielts_learning_save($1,2,$2)',[id,'{}']),/task_not_active/);
 await assert.rejects(db.query("update private.ielts_learning_submissions set score=6"),/immutable/);
 await assert.rejects(db.query("update private.ielts_learning_tasks set title='Changed'"),/immutable/);
});
test('teacher sharing is confirmed, complete, scoped, append-only and retry-safe',async()=>{
 const feedback={went_well:'You selected the confirmed day.',work_on:'Check the final starting time.',practice:'Listen for the corrected time.',check_again:'Try a fresh time-detail task.'};
 const req='00000000-0000-0000-0000-000000000104';
 await actor(student);await assert.rejects(db.query('select rpc_ielts_learning_review($1,$2,$3)',[id,JSON.stringify(feedback),req]),/not_authorized/);
 await actor(teacher);await assert.rejects(db.query('select rpc_ielts_learning_review($1,$2,$3)',[id,'{}',req]),/feedback_required/);
 await db.query('select rpc_ielts_learning_review($1,$2,$3)',[id,JSON.stringify(feedback),req]);await db.query('select rpc_ielts_learning_review($1,$2,$3)',[id,JSON.stringify(feedback),req]);
 assert.equal((await db.query('select count(*)::int n from private.ielts_learning_reviews')).rows[0].n,1);
 await actor(student);assert.equal((await detail()).review.reviewer,'Teacher');
 await db.exec('set role authenticated');await assert.rejects(db.query('select * from private.ielts_learning_tasks'),/permission denied/);await db.exec('reset role');
});
test('closed assignments reject saving, submission and incident writes',async()=>{
 await db.exec("update private.ielts_learning_allocations set status='closed'");await actor(student);
 await assert.rejects(db.query('select rpc_ielts_learning_submit($1,2)',[id]),/task_not_active/);
 await assert.rejects(db.query('select rpc_ielts_learning_incident($1,$2)',[id,'play']),/task_not_active/);
});
test('void source and previously exposed independent checks cannot generate fresh evidence',async()=>{
 await actor(teacher);await db.exec("update ielts_exam_attempts set status='void'");await assert.rejects(allocate(),/reviewed_source_required/);await db.exec("update ielts_exam_attempts set status='submitted'");
 const args=[school,student,'bh-ielts-targeted-listening-l2-v1',source,'Synthetic independent check integrity test.','00000000-0000-0000-0000-000000000105'];
 const q='select rpc_ielts_learning_allocate($1,$2,$3,$4,$5,null,$6) id';
 const result=(await db.query(q,args)).rows[0].id;assert.equal((await db.query(q,args)).rows[0].id,result);
 await db.query("update private.ielts_learning_allocations set status='closed' where id=$1",[result]);
 args[5]='00000000-0000-0000-0000-000000000106';await assert.rejects(db.query(q,args),/independent_check_already_exposed/);
});
test.after(()=>db.close());
