import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
const school=uuid(1),other=uuid(2),teacher=uuid(3),student=uuid(4),second=uuid(5),cls=uuid(6),assignment=uuid(7),item=uuid(8),target=uuid(9);
await db.exec(`create role anon;create role authenticated;create role service_role; create schema private;create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table users(id uuid primary key,username text,is_banned boolean default false);
create table school_members(school_id uuid,user_id uuid,status text);
create table classes(id uuid primary key,school_id uuid,class_name text);
create table class_students(class_id uuid,student_id uuid);
create table ielts_practice_assignments(id uuid primary key,school_id uuid,class_id uuid,title text,status text,due_at timestamptz);
create table ielts_practice_assignment_items(id uuid primary key,assignment_id uuid,content_type text,content_id text,title text,skill text);
create table ielts_practice_assignment_students(assignment_id uuid,student_id uuid,status text,created_at timestamptz);
create table ielts_practice_assignment_item_students(assignment_id uuid,assignment_item_id uuid,student_id uuid,status text,submitted_at timestamptz);
create table private.ielts_learning_allocations(id uuid primary key,school_id uuid,student_id uuid,task_code text,status text,created_at timestamptz,submitted_at timestamptz,due_at timestamptz,reason text);
create table private.ielts_learning_tasks(code text,version text,title text,skill text,purpose text,pilot_student uuid,success_description text,instructions text,content jsonb,content_sha256 text,requires_review boolean,questions jsonb);
create table private.ielts_learning_reviews(id uuid,allocation_id uuid,reviewed_at timestamptz);
create table private.ielts_learning_content_reviews(school_id uuid,task_code text,content_sha256 text);
create table academic_skill_registry_nodes(id uuid,name text);
create function public.can_manage_ielts_practice_school(uuid) returns boolean language sql as $$select $1='${school}'::uuid and auth.uid()='${teacher}'::uuid$$;
create function public.can_manage_ielts_practice_class(uuid,uuid) returns boolean language sql as $$select public.can_manage_ielts_practice_school($1) and exists(select 1 from public.classes where id=$2 and school_id=$1)$$;
create function public.can_manage_ielts_practice_assignment(uuid) returns boolean language sql as $$select exists(select 1 from public.ielts_practice_assignments where id=$1 and public.can_manage_ielts_practice_school(school_id))$$;
create function private.can_access_ielts_learning(uuid,boolean default false) returns boolean language sql as $$select exists(select 1 from private.ielts_learning_allocations where id=$1 and public.can_manage_ielts_practice_school(school_id))$$;
create function private.ielts_speaking_student_eligible(uuid) returns boolean language sql as $$select true$$;
insert into users(id,username) values('${teacher}','Teacher'),('${student}','Student A'),('${second}','Student B');
insert into school_members values('${school}','${student}','active'),('${school}','${second}','active');
insert into classes values('${cls}','${school}','Class 9');insert into class_students values('${cls}','${student}'),('${cls}','${second}');
insert into private.ielts_learning_tasks(code,version,title,skill,purpose,pilot_student,requires_review) values('exact-task','0.1.0','Same title','listening','guided_practice','${student}',false);
insert into private.ielts_learning_allocations(id,school_id,student_id,task_code,status,created_at,submitted_at) values('${target}','${school}','${student}','exact-task','submitted','2026-10-01','2026-10-02');
insert into private.ielts_learning_reviews values('${uuid(10)}','${target}','2026-10-03');
insert into ielts_practice_assignments values('${assignment}','${school}','${cls}','Class practice','assigned','2020-01-01');
insert into ielts_practice_assignment_items values('${item}','${assignment}','ielts_listening_set','school-material','Same title','listening');
insert into ielts_practice_assignment_students values('${assignment}','${student}','in_progress','2026-10-04'),('${assignment}','${second}','assigned','2026-10-04');
insert into ielts_practice_assignment_item_students values('${assignment}','${item}','${student}','in_progress','2026-10-05');
select set_config('request.jwt.claim.sub','${teacher}',false);`);
await db.exec(readFileSync('supabase/migrations/20261009084159_ielts_teacher_practice_history.sql','utf8'));
const actor=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const history=async(filters={})=>(await db.query('select rpc_ielts_teacher_practice_history($1,$2,$3,$4,$5,$6) d',[school,filters.search??'',filters.skill??'',filters.kind??'',filters.status??'',filters.offset??0])).rows[0].d;
const usage=async(items,recipient={student})=>(await db.query('select rpc_ielts_teacher_material_usage($1,$2,$3,$4) d',[school,JSON.stringify(items),recipient.student??null,recipient.classId??null])).rows[0].d;
test('both assignment types appear, with independent work/feedback states and no protected content',async()=>{
 const d=await history();assert.equal(d.rows.length,3);assert.equal(d.has_more,false);
 const t=d.rows.find(r=>r.kind==='targeted');assert.equal(t.status,'submitted');assert.equal(t.feedback_status,'shared');assert.equal(t.material_version,'0.1.0');
 const s=d.rows.find(r=>r.kind==='school'&&r.student_id===student);assert.equal(s.status,'submitted');assert.equal(s.feedback_status,'not_tracked');assert.equal(s.class_name,'Class 9');assert.equal(s.material_version,null);
 assert.doesNotMatch(JSON.stringify(d),/accepted_answers|response|recording|essay/);
 assert.equal((await history({search:'Student A',kind:'school'})).rows.length,1);
 assert.equal((await history({status:'overdue'})).rows.length,1);
 assert.equal((await history({status:'shared'})).rows.length,1);
});
test('usage uses exact identity rather than matching titles and includes current class members',async()=>{
 const d=await usage([{type:'targeted',id:'exact-task'},{type:'targeted',id:'new-task'},{type:'ielts_listening_set',id:'school-material'}]);
 assert.equal(d.find(r=>r.id==='exact-task').shared_count,1);assert.equal(d.find(r=>r.id==='new-task').assigned_count,0);assert.equal(d.find(r=>r.id==='school-material').assigned_count,1);
 const c=(await usage([{type:'ielts_listening_set',id:'school-material'}],{classId:cls}))[0];assert.equal(c.students_count,2);assert.equal(c.active_count,1);assert.equal(c.submitted_count,1);
 await db.exec(`update ielts_practice_assignments set status='archived' where id='${assignment}'`);
 const archived=(await usage([{type:'ielts_listening_set',id:'school-material'}],{classId:cls}))[0];assert.equal(archived.assigned_count,2);assert.equal(archived.active_count,0);assert.equal((await history({status:'archived'})).rows.length,2);
});
test('history is paginated; usage does not lose older exposure outside the first page',async()=>{
 for(let i=100;i<160;i++) await db.query("insert into private.ielts_learning_allocations(id,school_id,student_id,task_code,status,created_at) values($1,$2,$3,'exact-task','closed','2026-10-06')",[uuid(i),school,student]);
 const first=await history(),next=await history({offset:50});assert.equal(first.rows.length,50);assert.equal(first.has_more,true);assert.equal(next.rows.length,13);assert.equal(next.has_more,false);
 assert.equal(new Set([...first.rows,...next.rows].map(r=>r.row_id)).size,63);
 assert.equal((await usage([{type:'targeted',id:'exact-task'}]))[0].assigned_count,61);
});
test('students, cross-school requests, banned actors, bad recipient scope and public execution fail closed',async()=>{
 await actor(student);await assert.rejects(history(),/not_authorized/);await assert.rejects(usage([{type:'targeted',id:'exact-task'}]),/not_authorized/);
 await actor(teacher);await assert.rejects(db.query('select rpc_ielts_teacher_practice_history($1)',[other]),/not_authorized/);
 await assert.rejects(usage([{type:'targeted',id:'exact-task'}],{student:uuid(999)}),/not_authorized/);
 await assert.rejects(usage([{type:'targeted',id:'exact-task'}],{classId:uuid(999)}),/not_authorized/);
 await assert.rejects(usage([{type:'targeted',id:'exact-task'}],{student,classId:cls}),/recipient_scope_required/);
 await assert.rejects(history({offset:-1}),/invalid_filter/);
 await assert.rejects(usage(Array.from({length:51},()=>({type:'targeted',id:'exact-task'}))),/recipient_scope_required/);
 await db.exec(`update users set is_banned=true where id='${teacher}'`);await assert.rejects(history(),/not_authorized/);
 const p=(await db.query("select has_function_privilege('anon','public.rpc_ielts_teacher_practice_history(uuid,text,text,text,text,integer)','execute') anon,has_function_privilege('authenticated','private.ielts_teacher_practice_rows(uuid,uuid,uuid,jsonb)','execute') helper")).rows[0];assert.equal(p.anon,false);assert.equal(p.helper,false);
});
await test('close database',async()=>db.close());
