import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const student='b30e9c28-96f1-4d34-83e9-9b28b4926f42',teacher='54d6f8f8-8bb2-41e0-83a7-1afac5a21882';
const school='8eeecf5d-0496-4e0d-b5cd-538f91c9cfa0',source='00000000-0000-0000-0000-000000000101',outsider='00000000-0000-0000-0000-000000000102';
const request='00000000-0000-0000-0000-000000000103';let id;
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema private;create schema auth;create schema storage;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table users(id uuid primary key,username text,is_banned boolean default false);
create table ielts_exam_attempts(id uuid primary key,status text);
create table schools(id uuid primary key);create table school_members(school_id uuid,user_id uuid,status text);
create table academic_skill_registry_versions(id uuid primary key,status text);
create table academic_skill_registry_nodes(id uuid primary key,registry_version_id uuid,node_type text,status text,name text);
create table private.ielts_speaking_sessions(id uuid primary key,student_id uuid,school_id uuid,status text);
create table private.ielts_speaking_reviews(session_id uuid);
create table private.ielts_writing_screener_reviews(attempt_id uuid);
create table private.ielts_diagnostic_attempt_evidence(attempt_id uuid primary key,student_id uuid,school_id uuid,version_id uuid,form_snapshot jsonb);
create table private.ielts_diagnostic_versions(id uuid primary key,skills text[]);
create table private.ielts_diagnostic_scoring_runs(id uuid default gen_random_uuid(),attempt_id uuid,server_verified boolean,run_version int default 1,raw_score int,marks_possible int,integrity_state text,outcomes jsonb,submission_id uuid);
create table ielts_exam_submissions(id uuid,student_id uuid,payload jsonb);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(bucket_id text,name text);alter table storage.objects enable row level security;
create function private.ielts_speaking_student_eligible(uuid) returns boolean language sql as $$select $1='${student}'::uuid$$;
create function public.can_manage_ielts_practice_school(uuid) returns boolean language sql as $$select $1='${school}'::uuid and auth.uid()='${teacher}'::uuid$$;
insert into users(id,username) values('${student}','Pilot'),('${teacher}','Teacher'),('${outsider}','Outsider');
insert into ielts_exam_attempts values('${source}','submitted');
insert into schools values('${school}');insert into school_members values('${school}','${student}','active');
insert into academic_skill_registry_versions values('d4ad52b6-fd0f-4068-9982-28b89ff389c5','published');
insert into academic_skill_registry_nodes select unnest(array['0dbe1c8f-403a-493f-afd3-c219310fb18a','d5b1fddb-ba6f-4be1-8513-bb26d822357a','d0aa0bad-ecfa-4598-8f2f-07e93d3fa59b','f9064b63-e3f1-4bfa-8e8e-97a02756afb2']::uuid[]),'d4ad52b6-fd0f-4068-9982-28b89ff389c5','subskill','active','Listening construct';
insert into academic_skill_registry_versions values('ad250533-8582-4bc5-986b-32b0c9640a16','published');
insert into academic_skill_registry_nodes select unnest(array['bcddba69-28bc-436c-bb54-01a3c5733099','be5b2be3-ffb1-4cfb-95c8-cb9e3e9101de','ccaa0aaa-c3c0-47bf-b6cc-8aedbaed12b4','83fc3944-2f92-4cca-9a38-ac81f032627f','413181a5-95eb-4d96-82e0-c47c78e8de2a','1cea5568-701e-40ed-8459-61fd5df5263d']::uuid[]),'ad250533-8582-4bc5-986b-32b0c9640a16','subskill','active','Canonical construct';
insert into private.ielts_writing_screener_reviews values('${source}');
insert into private.ielts_speaking_sessions values('${source}','${student}','${school}','submitted');
insert into private.ielts_speaking_reviews values('${source}');
insert into private.ielts_diagnostic_versions values('${source}',array['listening','reading','writing']);
insert into private.ielts_diagnostic_attempt_evidence(attempt_id,student_id,school_id,version_id,form_snapshot) values('${source}','${student}','${school}','${source}', '{"items":[{"item_key":"q1","skill":"listening","prompt":"Which room?","accepted_answers":["lab"],"order_index":1,"taxonomy":{"name":"Final detail"}}]}');
insert into ielts_exam_submissions values('${source}','${student}','{"listening":{"q1":"hall"}}');
insert into private.ielts_diagnostic_scoring_runs(attempt_id,server_verified,raw_score,marks_possible,integrity_state,outcomes,submission_id) values('${source}',true,8,12,'clear','[{"item_key":"q1","skill":"listening","marks_awarded":0,"response_state":"answered"}]','${source}');`);
await db.exec(readFileSync('supabase/migrations/20261008195545_ielts_targeted_listening_pilot.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/20261008201324_ielts_learning_exposure_integrity.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/20261008202405_ielts_learning_school_boundary.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/20261008211134_ielts_four_skill_practice_pilot.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/20261009041408_ielts_listening_extension_02_reviewed_audio.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/20261009055444_ielts_targeted_teacher_review.sql','utf8'));

const second='00000000-0000-0000-0000-000000000201';
const secondSource='00000000-0000-0000-0000-000000000202';
await db.exec(`alter table users add column role text default 'student';
insert into users(id,username) values('${second}','Another student');
insert into school_members values('${school}','${second}','active');
create or replace function private.ielts_speaking_student_eligible(uuid) returns boolean language sql as $$select exists(select 1 from public.users where id=$1 and not is_banned and id in ('${student}','${second}'))$$;
insert into ielts_exam_attempts values('${secondSource}','submitted');
insert into private.ielts_diagnostic_attempt_evidence(attempt_id,student_id,school_id,version_id) values('${secondSource}','${second}','${school}','${source}');
insert into private.ielts_diagnostic_scoring_runs(attempt_id,server_verified) values('${secondSource}',true);
create function private.ielts_originality_payload(text,text) returns jsonb language sql as $$select jsonb_build_object('content_hash',coalesce(content_sha256,audio_sha256)) from private.ielts_learning_tasks where code=$2$$;
create function private.ielts_originality_label(text,text) returns text language sql as $$select 'Existing material'::text$$;
create function private.ielts_material_code(text,text) returns text language sql as $$select 'R-001'::text$$;`);
await db.exec(readFileSync('supabase/migrations/20261010022605_ielts_targeted_eligible_release.sql','utf8').split('-- Exact owner acceptance')[0]);
const actor=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const code='bh-ielts-targeted-reading-r1-v1';
const assign=(recipient=second,evidence=secondSource,task=code,req=crypto.randomUUID())=>db.query('select rpc_ielts_learning_allocate($1,$2,$3,$4,$5,null,$6) id',[school,recipient,task,evidence,'Actual teacher next step based on saved evidence.',req]);
test('new version release broadens recipients and reviewed content gate without rewriting the task',async()=>{
 await actor(teacher);await assert.rejects(assign(),/pilot_scope_only/);
 await db.query(`insert into private.ielts_learning_releases select code,content_sha256,version,audio_sha256,$1,now(),'{}' from private.ielts_learning_tasks where code=$2`,[teacher,code]);
 const request=crypto.randomUUID();const a=await assign(second,secondSource,code,request);assert.equal((await assign(second,secondSource,code,request)).rows[0].id,a.rows[0].id);
 const w=(await db.query('select rpc_ielts_learning_workspace($1) d',[school])).rows[0].d;
 assert.equal(w.tasks.find(t=>t.code===code).released,true);assert.equal(w.tasks.find(t=>t.code===code).approved,true);assert.equal(w.pilot_only,false);
 assert.equal((await db.query('select requires_review from private.ielts_learning_tasks where code=$1',[code])).rows[0].requires_review,true);
 await actor(second);const learner=(await db.query('select rpc_ielts_learning_workspace() d')).rows[0].d;assert.equal(learner.tasks.length,0);assert.ok(learner.allocations.some(t=>t.id===a.rows[0].id));assert.doesNotMatch(JSON.stringify(learner),/accepted_answers|teacher_notes/);
});
test('all-eligible scope retains entitlement, school, source evidence and unreleased-task denial',async()=>{
 await actor(second);await assert.rejects(assign(),/not_authorized/);await actor(teacher);
 await assert.rejects(assign(second,source),/reviewed_source_required/);
 await assert.rejects(assign(second,secondSource,'bh-ielts-targeted-writing-w1-v1'),/pilot_scope_only/);
 await db.exec(`update users set is_banned=true where id='${second}'`);await assert.rejects(assign(),/not_authorized/);await db.exec(`update users set is_banned=false where id='${second}'`);
 await db.exec(`delete from school_members where user_id='${second}'`);await assert.rejects(assign(),/not_authorized/);await db.exec(`insert into school_members values('${school}','${second}','active')`);
});
test('released independent checks remain single-exposure evidence',async()=>{
 await actor(teacher);const task='bh-ielts-targeted-reading-r2-v1';
 await db.query(`insert into private.ielts_learning_releases select code,content_sha256,version,audio_sha256,$1,now(),'{}' from private.ielts_learning_tasks where code=$2`,[teacher,task]);
 await assign(second,secondSource,task);
 await assert.rejects(assign(second,secondSource,task),/independent_check_already_exposed/);
});
test('release is bound to exact hash, unavailable on stale content and immutable/private',async()=>{
 assert.equal((await db.query('select private.ielts_learning_publicly_released($1) r',[code])).rows[0].r,true);
 await db.exec(`create or replace function private.ielts_originality_payload(text,text) returns jsonb language sql as $$select '{"content_hash":"changed"}'::jsonb$$;`);
 assert.equal((await db.query('select private.ielts_learning_publicly_released($1) r',[code])).rows[0].r,false);
 await assert.rejects(assign(),/pilot_scope_only/);
 await assert.rejects(db.exec('delete from private.ielts_learning_releases'),/immutable/);
 await db.exec('set role authenticated');await assert.rejects(db.exec('select * from private.ielts_learning_releases'),/permission denied/);await assert.rejects(db.query('select private.ielts_learning_publicly_released($1)',[code]),/permission denied/);await db.exec('reset role');
});
