import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite(), uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const student=uid(1),other=uid(2),school=uid(3),event=uid(4),form=uid(5),assignment=uid(6),attempt=uid(7);
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema auth;create schema private;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table users(id uuid primary key,school_id uuid,eligible boolean default true);
create table schools(id uuid primary key);create table classes(id uuid primary key);`);
const legacy=readFileSync('supabase/migrations/20260515120000_ielts_exam_mode_backend.sql','utf8');
await db.exec(legacy.slice(legacy.indexOf('create table if not exists public.ielts_exam_events'),legacy.indexOf('-- -----------------------------------------------------------------------------\n-- Scale indexes')));
await db.exec(`alter table ielts_exam_assignments add delivery_kind text default 'assigned';
create function private.ielts_exam_event_school(uuid) returns uuid language sql as $$select school_id from public.ielts_exam_events where id=$1$$;
create function private.actor_can_access_school_programme(uuid,text,boolean) returns boolean language sql as $$select coalesce((select eligible and school_id=$1 from public.users where id=auth.uid()),false)$$;
create function private.ielts_screener_release_eligible(uuid) returns boolean language sql as $$select coalesce((select eligible from public.users where id=auth.uid()),false)$$;
create function private.ielts_self_screener_assignment(uuid) returns boolean language sql as $$select exists(select 1 from public.ielts_exam_assignments a join public.users u on u.id=a.student_id where a.id=$1 and a.student_id=auth.uid() and a.delivery_kind='self_service' and u.eligible)$$;
create function public.rpc_ielts_submit_attempt_entitlement_internal(uuid,text,jsonb,text) returns jsonb language plpgsql as $$begin update public.ielts_exam_attempts set status='auto_submitted' where id=$1;return '{}'::jsonb;end$$;
insert into schools values('${school}'); insert into users values('${student}','${school}',true),('${other}',null,true);
insert into ielts_exam_events(id,school_id,title,status,starts_at,ends_at,duration_minutes) values('${event}','${school}','Fixture','live',now()-interval '1 minute',now()+interval '1 hour',60);
insert into ielts_exam_forms(id,exam_event_id,form_code,writing_payload,is_active) values('${form}','${event}','fixture','{"questions":[{"id":"essay"}]}',true);
insert into ielts_exam_assignments(id,exam_event_id,student_id,school_id,form_id) values('${assignment}','${event}','${student}','${school}','${form}');
insert into ielts_exam_attempts(id,assignment_id,exam_event_id,student_id,form_id,status,ends_at,lock_token,last_heartbeat_at) values('${attempt}','${assignment}','${event}','${student}','${form}','in_progress',now()+interval '1 hour','fixture',now()-interval '1 minute');
insert into ielts_exam_drafts(attempt_id,student_id,section,payload,draft_version) values('${attempt}','${student}','writing','{"essay":"Saved evidence"}',3);`);
const discovery=readFileSync('supabase/migrations/20261006093106_ielts_screener_discovery_and_self_start.sql','utf8');
await db.exec(discovery.slice(discovery.indexOf('create or replace function public.rpc_ielts_exam_whoami_entitlement_internal'),discovery.indexOf('revoke all on function public.rpc_ielts_exam_whoami_entitlement_internal')));
await db.exec(readFileSync('supabase/migrations/20261006143330_ielts_exam_select_latest_screener_assignment.sql','utf8'));
await db.exec(discovery.slice(discovery.indexOf('create function private.finalize_expired_ielts_screener'),discovery.indexOf('create or replace function public.rpc_ielts_start_attempt(p_assignment_id')));
await db.exec(readFileSync('supabase/migrations/20261008113107_ielts_compact_delivery_status.sql','utf8'));
const actor=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const status=async()=> (await db.query('select public.rpc_ielts_exam_status($1) result',[event])).rows[0].result;
async function parity(){const full=(await db.query('select public.rpc_ielts_exam_whoami($1) result',[event])).rows[0].result;const compact=await status();delete full.form_public_payload;delete full.drafts;delete full.server_now;delete full.remaining_seconds;const rest={...compact};delete rest.server_now;delete rest.remaining_seconds;assert.deepEqual(rest,full);assert.ok(!('drafts' in compact));assert.ok(!('form_public_payload' in compact));return compact;}
test('compact status preserves lifecycle, authorization, draft evidence and throttled presence',async()=>{
 await actor(student);assert.equal((await parity()).allowed,true);
 const heartbeat=(await db.query('select last_heartbeat_at from ielts_exam_attempts')).rows[0].last_heartbeat_at;
 await status();assert.deepEqual((await db.query('select last_heartbeat_at from ielts_exam_attempts')).rows[0].last_heartbeat_at,heartbeat);
 assert.deepEqual((await db.query('select payload,draft_version from ielts_exam_drafts')).rows[0],{payload:{essay:'Saved evidence'},draft_version:3});
 await db.exec("update ielts_exam_events set status='paused'");assert.equal((await parity()).event_status,'paused');
 await db.exec("update ielts_exam_events set status='live';update ielts_exam_attempts set status='submitted'");assert.equal((await parity()).attempt_status,'submitted');
 await db.exec("update ielts_exam_attempts set status='in_progress';update ielts_exam_assignments set status='void'");assert.equal((await parity()).reason,'assignment_void');
 await db.exec("update ielts_exam_assignments set status='assigned';update ielts_exam_forms set is_active=false");assert.equal((await parity()).reason,'form_unavailable');
 await db.exec('update ielts_exam_forms set is_active=true');await actor(other);assert.equal((await parity()).allowed,false);
 await actor(null);assert.equal((await status()).reason,'not_authenticated');
 await actor(student);await db.exec('update users set eligible=false');assert.equal((await parity()).reason,'ielts_not_in_school_agreement');
 await db.exec("update users set eligible=true;update ielts_exam_assignments set delivery_kind='self_service';update ielts_exam_attempts set ends_at=now()-interval '1 minute'");
 assert.equal((await status()).attempt_status,'auto_submitted');
 assert.equal((await db.query("select has_function_privilege('anon','public.rpc_ielts_exam_status(uuid)','execute') ok")).rows[0].ok,false);
 assert.equal((await db.query("select has_function_privilege('authenticated','public.rpc_ielts_exam_status(uuid)','execute') ok")).rows[0].ok,true);
 await db.close();
});
