import {JSDOM,VirtualConsole} from 'jsdom';
import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {randomUUID} from 'node:crypto';
const task={id:'00000000-0000-0000-0000-000000000201',title:'Pottery workshop',skill:'listening',purpose:'guided_practice',status:'in_progress',reviewed:false,reason:'Practise checking the final confirmed detail.',due_at:null};
const bundle=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{RouterProvider,createBrowserRouter}from'./src/lib/router';import{ supabase }from'./services/supabaseClient';import Home from './src/pages/ielts/IeltsHome';import Targeted from './src/pages/ielts/IeltsLearningPractice';import Assigned from './src/pages/ielts/IeltsAssignedPractice';const user={id:'00000000-0000-0000-0000-000000000001'};supabase.auth.getSession=async()=>({data:{session:{user}}});supabase.auth.getUser=async()=>({data:{user}});supabase.auth.onAuthStateChange=()=>({data:{subscription:{unsubscribe(){}}}});createRoot(document.getElementById('root')).render(<RouterProvider router={createBrowserRouter([{path:'/ielts',element:<Home/>},{path:'/ielts/practice/targeted',element:<Targeted/>},{path:'/ielts/practice/targeted/:id',element:<h1>Task opened</h1>},{path:'/ielts/practice/assigned',element:<Assigned/>}])}/>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,format:'iife',write:false,loader:{'.css':'empty'},define:{'import.meta':JSON.stringify({env:{VITE_SUPABASE_URL:'https://test.supabase.co',VITE_SUPABASE_ANON_KEY:'test-key'}})},logLevel:'silent'});
async function mount({path='/ielts',failPractice=false,denyCapability=false,optionalTools=false,tasks=[task]}={}){
 const calls=[],errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost'+path,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window;
 Object.assign(w,{TextEncoder,TextDecoder,Request,Response,Headers});w.crypto.randomUUID=randomUUID;w.HTMLMediaElement.prototype.pause=function(){};
 w.fetch=async(url,options)=>{const name=new URL(String(url)).pathname.split('/').pop();calls.push(name);let result;
  if(name==='users')result={role:'student',is_admin:false};
  else if(name==='school_admin_get_my_allocation_capabilities')result=denyCapability?{success:false,error:'unavailable'}:{success:true,school_id:'school',user_id:'student',role:'student',can_administer:false};
  else if(name==='rpc_ielts_learning_workspace'){if(failPractice){failPractice=false;return new Response(JSON.stringify({message:'test unavailable'}),{status:503,headers:{'Content-Type':'application/json'}});}result={manager:false,pilot_only:true,tasks:[],allocations:tasks};}
  else if(name==='rpc_ielts_starting_point_summary')return new Promise(()=>{}); // slow section must not block navigation or practice
  else if(name==='rpc_ielts_practice_student_assignments')result=[];
  else if(name.includes('funnel'))result=null;
  else {if(optionalTools)return new Promise(()=>{});errors.push('Unexpected request '+name);return new Response(JSON.stringify({message:'unexpected'}),{status:500,headers:{'Content-Type':'application/json'}});}
  return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});
 };
 w.eval(bundle.outputFiles[0].text);const wait=async fn=>{for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,15));}throw Error('UI did not settle '+w.document.body.textContent+' '+errors.join(','));};
 return{dom,w,calls,errors,wait};
}
test('school workspace shows direct targeted task while screeners are slow, without catalogue or billing requests',async()=>{
 const m=await mount();try{await m.wait(()=>m.w.document.body.textContent.includes('Pottery workshop'));const nav=m.w.document.querySelector('nav[aria-label="IELTS navigation"]');assert.equal(nav.querySelectorAll('a').length,4);assert.equal(nav.querySelector('[aria-current="page"]').textContent.includes('Screeners'),true);assert.equal(m.calls.filter(c=>c==='rpc_ielts_learning_workspace').length,1);assert.equal(m.calls.filter(c=>c==='rpc_ielts_starting_point_summary').length,1);assert.doesNotMatch(m.calls.join(' '),/subscription|ielts_reading_sets|ielts_listening_sets|ielts_user|extra_practice|tier/);m.w.document.querySelector('.it-task button').click();await m.wait(()=>m.w.location.pathname.endsWith(task.id));assert.match(m.w.document.body.textContent,/Task opened/);assert.deepEqual(m.errors,[]);}finally{m.dom.window.close();}
});
test('targeted tab opens the real assigned task list and preserves completed feedback and closed labels',async()=>{
 const m=await mount({tasks:[task,{...task,id:'second',title:'Reviewed work',status:'submitted',reviewed:true},{...task,id:'third',title:'Closed work',status:'closed'}]});try{await m.wait(()=>m.w.document.querySelector('.it-task'));m.w.document.querySelector('a[href="/ielts/practice/targeted"]').click();await m.wait(()=>m.w.location.pathname==='/ielts/practice/targeted'&&m.w.document.querySelector('h1')?.textContent==='Targeted Practice'&&m.w.document.querySelectorAll('.it-task').length===3);assert.match(m.w.document.body.textContent,/Continue task|Teacher feedback ready|Closed · saved work/);assert.equal(m.w.document.querySelector('[aria-current="page"]').textContent.includes('Targeted Practice'),true);assert.equal(m.calls.filter(c=>c==='rpc_ielts_learning_workspace').length,2);assert.deepEqual(m.errors,[]);}finally{m.dom.window.close();}
});
test('targeted failure stays distinct from empty assignments and retries independently of slow screeners',async()=>{
 const m=await mount({failPractice:true});try{await m.wait(()=>m.w.document.body.textContent.includes('Try targeted practice again'));assert.doesNotMatch(m.w.document.body.textContent,/No targeted tasks yet/);[...m.w.document.querySelectorAll('button')].find(b=>b.textContent==='Try targeted practice again').click();await m.wait(()=>m.w.document.body.textContent.includes(task.title));assert.equal(m.calls.filter(c=>c==='rpc_ielts_learning_workspace').length,2);assert.equal(m.calls.filter(c=>c==='rpc_ielts_starting_point_summary').length,1);assert.deepEqual(m.errors,[]);}finally{m.dom.window.close();}
});
test('empty school assignment page explains the separate targeted section and navigates there',async()=>{
 const m=await mount({path:'/ielts/practice/assigned'});try{await m.wait(()=>m.w.document.body.textContent.includes('No school assignment sets right now'));assert.doesNotMatch(m.w.document.body.textContent,/No IELTS practice has been assigned/);[...m.w.document.querySelectorAll('button')].find(b=>b.textContent==='Open Targeted Practice →').click();await m.wait(()=>m.w.location.pathname==='/ielts/practice/targeted'&&m.w.document.body.textContent.includes(task.title));assert.equal(m.calls.some(c=>c==='rpc_ielts_practice_assignment_progress'),false);assert.deepEqual(m.errors,[]);}finally{m.dom.window.close();}
});
test('unverified school capability never opens student tasks or school administration',async()=>{
 const m=await mount({denyCapability:true});try{await m.wait(()=>m.w.document.body.textContent.includes('Your IELTS access could not be verified.'));assert.equal(m.calls.includes('rpc_ielts_learning_workspace'),false);assert.equal(m.calls.includes('rpc_ielts_starting_point_summary'),false);assert.equal(m.w.document.querySelector('.it-task'),null);assert.deepEqual(m.errors,[]);}finally{m.dom.window.close();}
});

test('optional catalogue requests stay deferred until the student chooses other practice tools',async()=>{
 const m=await mount({optionalTools:true});try{await m.wait(()=>m.w.document.body.textContent.includes(task.title));assert.equal(m.calls.includes('get_effective_tier'),false);[...m.w.document.querySelectorAll('button')].find(b=>b.textContent==='Explore other practice tools →').click();await m.wait(()=>m.w.location.search==='?view=library'&&m.calls.includes('get_effective_tier'));assert.match(m.w.document.body.textContent,/Loading your IELTS dashboard/);m.w.history.replaceState(null,'','/ielts');m.w.dispatchEvent(new m.w.PopStateEvent('popstate'));await m.wait(()=>m.w.document.body.textContent.includes(task.title));assert.deepEqual(m.errors,[]);}finally{m.dom.window.close();}
});
