import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
const questionBankStyles = readFileSync('components/teacher/QuestionBank.css', 'utf8');
const schoolDocument = readFileSync('src/lib/schoolDocument.ts', 'utf8');
test('question bank topic modal owns its action styling and responsive hierarchy', () => {
    const actionButtonRule = questionBankStyles.match(/\.qb-modal__header-actions>button\{([^}]*)\}/s)?.[1] ?? '';
    assert.ok(actionButtonRule, 'expected the topic modal action button rule');
    assert.match(actionButtonRule, /border:1px solid #cbd5e1/);
    assert.match(actionButtonRule, /background:#fff/);
    assert.match(actionButtonRule, /color:#334155/);
    assert.match(actionButtonRule, /font-weight:800/);
    const assignmentRule = questionBankStyles.match(/\.qb-modal__assign\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(assignmentRule, /background:linear-gradient\(135deg,#2563eb,#4f46e5\)!important/);
    assert.match(assignmentRule, /color:#fff!important/);
    assert.match(questionBankStyles, /@media\(max-width:720px\)\{[\s\S]*?\.qb-modal__header-actions\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
    const closeRule = questionBankStyles.match(/\.qb-modal__close\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(closeRule, /background:#fff!important/);
    assert.match(closeRule, /color:#475569!important/);
});
test('school document printing uses flow-aware repeated table header and footer groups', () => {
    assert.match(schoolDocument, /margin:14mm 15mm 14mm/);
    assert.match(schoolDocument, /class="school-document__print-frame"/);
    assert.match(schoolDocument, /class="school-document__print-head"/);
    assert.match(schoolDocument, /class="school-document__print-foot"/);
    const printCss = schoolDocument.match(/@media print\{([\s\S]*?)\n  \}/)?.[1] ?? '';
    assert.ok(printCss, 'expected print-specific school document CSS');
    const frameRule = printCss.match(/\.school-document__print-frame\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(frameRule, /display:table/);
    assert.match(frameRule, /table-layout:fixed/);
    const headRule = printCss.match(/\.school-document__print-frame>thead\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(headRule, /display:table-header-group/);
    const footRule = printCss.match(/\.school-document__print-frame>tfoot\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(footRule, /display:table-footer-group/);
    const headerRule = printCss.match(/\.school-document__repeating-header\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(headerRule, /position:static/);
    assert.match(headerRule, /min-height:15mm/);
    assert.doesNotMatch(headerRule, /top:-/);
    assert.doesNotMatch(headerRule, /position:fixed/);
    const footerRule = printCss.match(/\.school-document__page-footer\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(footerRule, /position:static/);
    assert.doesNotMatch(footerRule, /bottom:-/);
    assert.doesNotMatch(footerRule, /position:fixed/);
    const cardRule = schoolDocument.match(/\.school-document__body \.document-card\{([^}]*)\}/s)?.[1] ?? '';
    assert.match(cardRule, /break-inside:avoid-page/);
    assert.match(cardRule, /page-break-inside:avoid/);
    assert.doesNotMatch(schoolDocument, /top:-20mm/);
    assert.doesNotMatch(schoolDocument, /bottom:-12mm/);
});
