import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../services/supabaseClient';

type SkillTab = 'reading' | 'listening' | 'writing' | 'speaking';
type Q = { question_order:number; question_type:string; body:string; options:string; correct_answer:string; explanation:string };
type ReadingDraft = { id?:string; title:string; slug:string; description:string; level:string; est_band_min:string; est_band_max:string; duration_minutes:string; passage_text:string; is_active:boolean; questions:Q[] };
type ListeningDraft = { id?:string; title:string; slug:string; description:string; level:string; est_band_min:string; est_band_max:string; duration_minutes:string; audio_url:string; is_active:boolean; instructions:string; example_prompt:string; example_answer:string; section_label:string; question_range_label:string; questions:Q[] };
type WritingDraft = { id?:string; slug:string; task_type:string; title:string; prompt:string; bands_target:string; sample_answer:string; is_active:boolean }
type SpeakingDraft = { id?:string; slug:string; part:string; prompt:string; follow_ups:string; is_active:boolean }
type ContentItem = { id:string; title:string; skill:SkillTab; is_active:boolean; difficulty?:string|null; created_at?:string|null; ready_to_assign?:boolean; warnings?:string[] };
const tabs: SkillTab[] = ['reading','listening','writing','speaking'];
const qBlank=(n:number):Q=>({question_order:n,question_type:'short_answer',body:'',options:'',correct_answer:'',explanation:''});
const blankReading=():ReadingDraft=>({title:'',slug:'',description:'',level:'',est_band_min:'',est_band_max:'',duration_minutes:'60',passage_text:'',is_active:false,questions:[]});
const blankListening=():ListeningDraft=>({title:'',slug:'',description:'',level:'',est_band_min:'',est_band_max:'',duration_minutes:'30',audio_url:'',is_active:false,instructions:'',example_prompt:'',example_answer:'',section_label:'',question_range_label:'',questions:[]});
const blankWriting=():WritingDraft=>({slug:'',task_type:'',title:'',prompt:'',bands_target:'',sample_answer:'',is_active:false});
const blankSpeaking=():SpeakingDraft=>({slug:'',part:'1',prompt:'',follow_ups:'',is_active:false});

const IeltsContentManager: React.FC = () => {
const [activeTab,setActiveTab]=useState<SkillTab>('reading'); const [items,setItems]=useState<ContentItem[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false);
const [editingListening,setEditingListening]=useState<ListeningDraft|null>(null); const [editingReading,setEditingReading]=useState<ReadingDraft|null>(null); const [editingWriting,setEditingWriting]=useState<WritingDraft|null>(null); const [editingSpeaking,setEditingSpeaking]=useState<SpeakingDraft|null>(null);
const load = async()=>{ setLoading(true); setError(null); const {data,error:rpcError}=await supabase.rpc('rpc_ielts_content_list'); if(rpcError){setError(rpcError.message);setLoading(false);return;} setItems(Array.isArray(data)?data:[]); setLoading(false);};
useEffect(()=>{ void load(); },[]);
const filtered=useMemo(()=>items.filter(i=>i.skill===activeTab&&i.title.toLowerCase().includes(query.toLowerCase())),[items,activeTab,query]);

const saveReading=async()=>{ if(!editingReading)return; setSaving(true); setError(null); const {data:r,error:e}=await supabase.rpc('rpc_ielts_content_upsert_reading_set',{p_id:editingReading.id?Number(editingReading.id):null,p_title:editingReading.title,p_slug:editingReading.slug||null,p_description:editingReading.description||null,p_level:editingReading.level,p_est_band_min:editingReading.est_band_min?Number(editingReading.est_band_min):null,p_est_band_max:editingReading.est_band_max?Number(editingReading.est_band_max):null,p_duration_minutes:Number(editingReading.duration_minutes),p_passage_text:editingReading.passage_text||null,p_is_active:editingReading.is_active}); if(e){setError(e.message);setSaving(false);return;} const setId=Number(r?.id); const qs=editingReading.questions.map(q=>({question_order:q.question_order,question_type:q.question_type,body:q.body,options:q.options?JSON.parse(q.options):null,correct_answer:q.correct_answer?JSON.parse(q.correct_answer):null,explanation:q.explanation||null})); const {error:qe}=await supabase.rpc('rpc_ielts_content_replace_reading_questions',{p_reading_set_id:setId,p_questions:qs}); if(qe){setError(qe.message);setSaving(false);return;} setEditingReading(null); setSaving(false); await load(); };
const saveWriting=async()=>{ if(!editingWriting)return; setSaving(true); setError(null); const {error:e}=await supabase.rpc('rpc_ielts_content_upsert_writing_task',{p_id:editingWriting.id?Number(editingWriting.id):null,p_slug:editingWriting.slug||null,p_task_type:editingWriting.task_type||null,p_title:editingWriting.title,p_prompt:editingWriting.prompt,p_bands_target:editingWriting.bands_target||null,p_sample_answer:editingWriting.sample_answer||null,p_is_active:editingWriting.is_active}); if(e){setError(e.message);setSaving(false);return;} setEditingWriting(null); setSaving(false); await load(); };
const saveSpeaking=async()=>{ if(!editingSpeaking)return; setSaving(true); setError(null); const {error:e}=await supabase.rpc('rpc_ielts_content_upsert_speaking_task',{p_id:editingSpeaking.id?Number(editingSpeaking.id):null,p_slug:editingSpeaking.slug||null,p_part:Number(editingSpeaking.part),p_prompt:editingSpeaking.prompt,p_follow_ups:editingSpeaking.follow_ups?JSON.parse(editingSpeaking.follow_ups):null,p_is_active:editingSpeaking.is_active}); if(e){setError(e.message);setSaving(false);return;} setEditingSpeaking(null); setSaving(false); await load(); };
const saveListening=async()=>{ if(!editingListening)return; setSaving(true); setError(null); const {data:r,error:e}=await supabase.rpc('rpc_ielts_content_upsert_listening_set',{p_id:editingListening.id?Number(editingListening.id):null,p_title:editingListening.title,p_slug:editingListening.slug||null,p_description:editingListening.description||null,p_level:editingListening.level,p_est_band_min:editingListening.est_band_min?Number(editingListening.est_band_min):null,p_est_band_max:editingListening.est_band_max?Number(editingListening.est_band_max):null,p_duration_minutes:Number(editingListening.duration_minutes),p_audio_url:editingListening.audio_url||null,p_is_active:editingListening.is_active,p_instructions:editingListening.instructions||null,p_example_prompt:editingListening.example_prompt||null,p_example_answer:editingListening.example_answer||null,p_section_label:editingListening.section_label||null,p_question_range_label:editingListening.question_range_label||null}); if(e){setError(e.message);setSaving(false);return;} const setId=Number(r?.id); const qs=editingListening.questions.map(q=>({question_order:q.question_order,question_type:q.question_type,body:q.body,options:q.options?JSON.parse(q.options):null,correct_answer:q.correct_answer?JSON.parse(q.correct_answer):null,explanation:q.explanation||null})); const {error:qe}=await supabase.rpc('rpc_ielts_content_replace_listening_questions',{p_listening_set_id:setId,p_questions:qs}); if(qe){setError(qe.message);setSaving(false);return;} setEditingListening(null); setSaving(false); await load(); };

const loadReading=async(id:string)=>{const {data:s,error}=await supabase.from('ielts_reading_sets').select('*').eq('id',Number(id)).single(); if(error){setError(error.message);return;} const {data:q}=await supabase.from('ielts_reading_questions').select('question_order,question_type,body,options,correct_answer,explanation').eq('set_id',Number(id)).order('question_order'); setEditingReading({id,title:s.title??'',slug:s.slug??'',description:s.description??'',level:s.level??'',est_band_min:s.est_band_min?.toString()??'',est_band_max:s.est_band_max?.toString()??'',duration_minutes:String(s.duration_minutes??60),passage_text:s.passage_text??'',is_active:Boolean(s.is_active),questions:(q??[]).map((x:any)=>({question_order:x.question_order,question_type:x.question_type??'short_answer',body:x.body??'',options:x.options?JSON.stringify(x.options):'',correct_answer:x.correct_answer?JSON.stringify(x.correct_answer):'',explanation:x.explanation??''}))});};
const loadWriting=async(id:string)=>{const {data:s,error}=await supabase.from('ielts_writing_tasks').select('id,slug,task_type,title,prompt,bands_target,sample_answer,is_active').eq('id',Number(id)).single(); if(error){setError(error.message);return;} setEditingWriting({id,slug:s.slug??'',task_type:s.task_type??'',title:s.title??'',prompt:s.prompt??'',bands_target:s.bands_target??'',sample_answer:s.sample_answer??'',is_active:Boolean(s.is_active)});};
const loadSpeaking=async(id:string)=>{const {data:s,error}=await supabase.from('ielts_speaking_tasks').select('id,slug,part,prompt,follow_ups,is_active').eq('id',Number(id)).single(); if(error){setError(error.message);return;} setEditingSpeaking({id,slug:s.slug??'',part:String(s.part??1),prompt:s.prompt??'',follow_ups:s.follow_ups?JSON.stringify(s.follow_ups):'',is_active:Boolean(s.is_active)});};
const loadListening=async(id:string)=>{const {data:s,error}=await supabase.from('ielts_listening_sets').select('*').eq('id',Number(id)).single(); if(error){setError(error.message);return;} const {data:q}=await supabase.from('ielts_listening_questions').select('question_order,question_type,body,options,correct_answer,explanation').eq('listening_set_id',Number(id)).order('question_order'); setEditingListening({id,title:s.title??'',slug:s.slug??'',description:s.description??'',level:s.level??'',est_band_min:s.est_band_min?.toString()??'',est_band_max:s.est_band_max?.toString()??'',duration_minutes:String(s.duration_minutes??30),audio_url:s.audio_url??'',is_active:Boolean(s.is_active),instructions:s.instructions??'',example_prompt:s.example_prompt??'',example_answer:s.example_answer??'',section_label:s.section_label??'',question_range_label:s.question_range_label??'',questions:(q??[]).map((x:any)=>({question_order:x.question_order,question_type:x.question_type??'short_answer',body:x.body??'',options:x.options?JSON.stringify(x.options):'',correct_answer:x.correct_answer?JSON.stringify(x.correct_answer):'',explanation:x.explanation??''}))});};

return <div className="space-y-4 rounded-xl border border-emerald-400/40 bg-slate-950/70 p-4"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-emerald-300">IELTS Content</h2><input className="rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" placeholder="Search title" value={query} onChange={e=>setQuery(e.target.value)} /></div><div className="flex gap-2">{tabs.map(t=><button key={t} onClick={()=>setActiveTab(t)} className={`rounded px-3 py-1 text-sm ${t===activeTab?'bg-emerald-500 text-black':'bg-slate-800 text-slate-200'}`}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{activeTab==='reading'&&<button onClick={()=>setEditingReading(blankReading())} className="rounded bg-cyan-500 px-3 py-1 text-sm font-semibold text-black">New Reading Task</button>}{activeTab==='listening'&&<button onClick={()=>setEditingListening(blankListening())} className="rounded bg-cyan-500 px-3 py-1 text-sm font-semibold text-black">New Listening Task</button>}
{activeTab==='writing'&&<button onClick={()=>setEditingWriting(blankWriting())} className="rounded bg-cyan-500 px-3 py-1 text-sm font-semibold text-black">New Writing Task</button>}
{activeTab==='speaking'&&<button onClick={()=>setEditingSpeaking(blankSpeaking())} className="rounded bg-cyan-500 px-3 py-1 text-sm font-semibold text-black">New Speaking Task</button>}
{editingReading&&<div className="space-y-2 rounded border border-cyan-500/40 p-3"><p className="font-semibold text-cyan-300">Reading Editor</p><input className="w-full rounded bg-slate-900 p-2" placeholder="title" value={editingReading.title} onChange={e=>setEditingReading({...editingReading,title:e.target.value})}/><input className="w-full rounded bg-slate-900 p-2" placeholder="level" value={editingReading.level} onChange={e=>setEditingReading({...editingReading,level:e.target.value})}/><textarea className="w-full rounded bg-slate-900 p-2" placeholder="passage_text" value={editingReading.passage_text} onChange={e=>setEditingReading({...editingReading,passage_text:e.target.value})}/><label className="text-sm text-slate-200"><input type="checkbox" checked={editingReading.is_active} onChange={e=>setEditingReading({...editingReading,is_active:e.target.checked})}/> Active</label>{editingReading.questions.map((q,idx)=><div key={idx} className="rounded border border-slate-700 p-2"><input className="w-full rounded bg-slate-900 p-1" value={q.body} placeholder="question body" onChange={e=>{const n=[...editingReading.questions];n[idx]={...q,body:e.target.value};setEditingReading({...editingReading,questions:n});}}/><input className="w-full rounded bg-slate-900 p-1" value={q.correct_answer} placeholder="correct_answer JSON" onChange={e=>{const n=[...editingReading.questions];n[idx]={...q,correct_answer:e.target.value};setEditingReading({...editingReading,questions:n});}}/><div className="mt-1 flex gap-2"><button className="rounded bg-slate-700 px-2 py-1 text-xs" onClick={()=>{const n=editingReading.questions.filter((_,i)=>i!==idx).map((x,i)=>({...x,question_order:i+1}));setEditingReading({...editingReading,questions:n});}}>Remove</button></div></div>)}<div className="flex gap-2"><button className="rounded bg-slate-700 px-2 py-1 text-xs" onClick={()=>setEditingReading({...editingReading,questions:[...editingReading.questions,qBlank(editingReading.questions.length+1)]})}>Add Question</button><button className="rounded bg-emerald-500 px-2 py-1 text-xs font-semibold text-black" onClick={()=>void saveReading()} disabled={saving}>{saving?'Saving…':'Save'}</button></div></div>}
{editingWriting&&<div className="space-y-2 rounded border border-cyan-500/40 p-3"><p className="font-semibold text-cyan-300">Writing Editor</p><input className="w-full rounded bg-slate-900 p-2" placeholder="title" value={editingWriting.title} onChange={e=>setEditingWriting({...editingWriting,title:e.target.value})}/><input className="w-full rounded bg-slate-900 p-2" placeholder="task_type" value={editingWriting.task_type} onChange={e=>setEditingWriting({...editingWriting,task_type:e.target.value})}/><textarea className="w-full rounded bg-slate-900 p-2" placeholder="prompt" value={editingWriting.prompt} onChange={e=>setEditingWriting({...editingWriting,prompt:e.target.value})}/><input className="w-full rounded bg-slate-900 p-2" placeholder="bands_target" value={editingWriting.bands_target} onChange={e=>setEditingWriting({...editingWriting,bands_target:e.target.value})}/><textarea className="w-full rounded bg-slate-900 p-2" placeholder="sample_answer" value={editingWriting.sample_answer} onChange={e=>setEditingWriting({...editingWriting,sample_answer:e.target.value})}/><label className="text-sm text-slate-200"><input type="checkbox" checked={editingWriting.is_active} onChange={e=>setEditingWriting({...editingWriting,is_active:e.target.checked})}/> Active</label><button className="rounded bg-emerald-500 px-2 py-1 text-xs font-semibold text-black" onClick={()=>void saveWriting()} disabled={saving}>{saving?'Saving…':'Save'}</button></div>}
{editingSpeaking&&<div className="space-y-2 rounded border border-cyan-500/40 p-3"><p className="font-semibold text-cyan-300">Speaking Editor</p><input className="w-full rounded bg-slate-900 p-2" placeholder="part" value={editingSpeaking.part} onChange={e=>setEditingSpeaking({...editingSpeaking,part:e.target.value})}/><textarea className="w-full rounded bg-slate-900 p-2" placeholder="prompt" value={editingSpeaking.prompt} onChange={e=>setEditingSpeaking({...editingSpeaking,prompt:e.target.value})}/><textarea className="w-full rounded bg-slate-900 p-2" placeholder="follow_ups JSON" value={editingSpeaking.follow_ups} onChange={e=>setEditingSpeaking({...editingSpeaking,follow_ups:e.target.value})}/><label className="text-sm text-slate-200"><input type="checkbox" checked={editingSpeaking.is_active} onChange={e=>setEditingSpeaking({...editingSpeaking,is_active:e.target.checked})}/> Active</label><button className="rounded bg-emerald-500 px-2 py-1 text-xs font-semibold text-black" onClick={()=>void saveSpeaking()} disabled={saving}>{saving?'Saving…':'Save'}</button></div>}
{editingListening&&<div className="space-y-2 rounded border border-cyan-500/40 p-3"><p className="font-semibold text-cyan-300">Listening Editor</p><input className="w-full rounded bg-slate-900 p-2" placeholder="title" value={editingListening.title} onChange={e=>setEditingListening({...editingListening,title:e.target.value})}/><input className="w-full rounded bg-slate-900 p-2" placeholder="level" value={editingListening.level} onChange={e=>setEditingListening({...editingListening,level:e.target.value})}/><input className="w-full rounded bg-slate-900 p-2" placeholder="audio_url" value={editingListening.audio_url} onChange={e=>setEditingListening({...editingListening,audio_url:e.target.value})}/><label className="text-sm text-slate-200"><input type="checkbox" checked={editingListening.is_active} onChange={e=>setEditingListening({...editingListening,is_active:e.target.checked})}/> Active</label><div className="flex gap-2"><button className="rounded bg-slate-700 px-2 py-1 text-xs" onClick={()=>setEditingListening({...editingListening,questions:[...editingListening.questions,qBlank(editingListening.questions.length+1)]})}>Add Question</button><button className="rounded bg-emerald-500 px-2 py-1 text-xs font-semibold text-black" onClick={()=>void saveListening()} disabled={saving}>{saving?'Saving…':'Save'}</button></div></div>}
{loading&&<p className="text-slate-300">Loading…</p>}{error&&<p className="text-red-300">{error}</p>}<div className="space-y-2">{filtered.map(item=><div key={`${item.skill}-${item.id}`} className="rounded border border-slate-700 bg-slate-900/60 p-3"><div className="flex items-center justify-between"><div><p className="font-semibold text-white">{item.title}</p><p className="text-xs text-slate-400">{item.skill} · {item.difficulty??'—'} · {item.created_at?new Date(item.created_at).toLocaleDateString():'—'}</p></div><div className="flex items-center gap-2">{item.skill==='listening'&&<button className="rounded bg-slate-700 px-2 py-1 text-xs" onClick={()=>void loadListening(item.id)}>Edit</button>}{item.skill==='reading'&&<button className="rounded bg-slate-700 px-2 py-1 text-xs" onClick={()=>void loadReading(item.id)}>Edit</button>}{item.skill==='writing'&&<button className="rounded bg-slate-700 px-2 py-1 text-xs" onClick={()=>void loadWriting(item.id)}>Edit</button>}{item.skill==='speaking'&&<button className="rounded bg-slate-700 px-2 py-1 text-xs" onClick={()=>void loadSpeaking(item.id)}>Edit</button>}<span className={`text-xs ${item.is_active?'text-emerald-300':'text-amber-300'}`}>{item.is_active?'Active':'Inactive'}</span></div></div><div className="mt-2 flex flex-wrap gap-2 text-xs">{item.ready_to_assign&&<span className="rounded bg-emerald-700/40 px-2 py-1 text-emerald-200">Ready to assign</span>}{(item.warnings??[]).map(w=><span key={w} className="rounded bg-amber-700/30 px-2 py-1 text-amber-200">{w}</span>)}</div></div>)}</div></div>;
};

export default IeltsContentManager;
