/**
 * Extract QUESTIONS arrays from Cambridge test HTML files
 * and generate a TypeScript module for teacher answer review.
 *
 * Usage: node scripts/extractQuestionData.js
 */
const fs = require('fs');
const path = require('path');

const TESTS_DIR = path.join(__dirname, '..', 'public', 'cambridge-tests');
const OUTPUT_FILE = path.join(__dirname, '..', 'components', 'cambridgeQuestionData.ts');

// Walk directories to find HTML files
function walkDir(dir) {
  let results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(walkDir(full));
    } else if (entry.name.endsWith('.html') && entry.name !== 'index.html') {
      results.push(full);
    }
  }
  return results;
}

function extractFromFile(filePath) {
  const html = fs.readFileSync(filePath, 'utf-8');

  // Extract QUIZ_BASE_NAME
  const baseNameMatch = html.match(/const\s+QUIZ_BASE_NAME\s*=\s*['"`]([^'"`]+)['"`]/);
  if (!baseNameMatch) return null;
  const baseName = baseNameMatch[1];

  // Extract QUESTIONS array - find the start
  const questionsStart = html.indexOf('let QUESTIONS = [');
  if (questionsStart === -1) return null;

  // Find the matching closing bracket
  let depth = 0;
  let started = false;
  let arrayStart = -1;
  let arrayEnd = -1;
  for (let i = questionsStart; i < html.length; i++) {
    if (html[i] === '[') {
      if (!started) {
        started = true;
        arrayStart = i;
      }
      depth++;
    } else if (html[i] === ']') {
      depth--;
      if (depth === 0) {
        arrayEnd = i + 1;
        break;
      }
    }
  }

  if (arrayStart === -1 || arrayEnd === -1) return null;

  let arrayStr = html.substring(arrayStart, arrayEnd);

  // FIRST: Replace all possessive apostrophes that break JS single-quoted strings
  // Pattern 1: word's (e.g., Fehling's, Hess's, Le Chatelier's)
  arrayStr = arrayStr.replace(/([a-zA-Z])'s(\s|[^a-zA-Z])/g, '$1\\u2019s$2');
  // Pattern 2: words ending in 's followed by space/word (e.g., Tollens' reagent)
  // Match letter-s-apostrophe followed by space then lowercase letter (mid-sentence indicator)
  arrayStr = arrayStr.replace(/([a-zA-Z]s)' ([a-z])/g, '$1\\u2019 $2');
  // Pattern 3: contractions (don't, won't, can't, isn't, it's, doesn't, aren't)
  arrayStr = arrayStr.replace(/([a-zA-Z])n'(t[\s,.'"\)])/g, '$1n\\u2019$2');
  // Pattern 4: Tollens' at end of attribute value (before closing quote + comma/bracket)
  arrayStr = arrayStr.replace(/([a-zA-Z]s)'\s*'/g, "$1\\u2019'");

  // Remove 'explanation' fields entirely since they aren't needed for the teacher view
  arrayStr = arrayStr.replace(/,?\s*explanation\s*:\s*'[^]*?(?<!\\)'/g, (m) => {
    if ((m.match(/'/g) || []).length >= 2) return '';
    return m;
  });
  arrayStr = arrayStr.replace(/,?\s*explanation\s*:\s*"[^]*?(?<!\\)"/g, (m) => {
    if ((m.match(/"/g) || []).length >= 2) return '';
    return m;
  });
  arrayStr = arrayStr.replace(/,?\s*explanation\s*:\s*`[^]*?(?<!\\)`/g, '');
  
  // Wrap in a function to safely evaluate
  try {
    const fn = new Function(`return ${arrayStr}`);
    const questions = fn();
    
    return {
      baseName,
      questions: questions.map(q => ({
        number: q.number,
        prompt: q.prompt || '',
        options: q.options || null,
        table: q.table || null,
        image: q.image || null,
      }))
    };
  } catch (e) {
    console.warn(`  Failed to parse QUESTIONS from ${path.basename(filePath)}: ${e.message}`);
    return { baseName, questions: [], error: e.message };
  }
}

console.log('Scanning for HTML test files...');
const htmlFiles = walkDir(TESTS_DIR);
console.log(`Found ${htmlFiles.length} HTML files`);

const allTests = {};
let successCount = 0;
let failCount = 0;

for (const file of htmlFiles) {
  const rel = path.relative(TESTS_DIR, file);
  const result = extractFromFile(file);
  if (!result) {
    console.log(`  SKIP ${rel} (no QUESTIONS array or no QUIZ_BASE_NAME)`);
    continue;
  }
  if (result.error) {
    console.log(`  FAIL ${rel}: ${result.error}`);
    failCount++;
    continue;
  }
  
  console.log(`  OK   ${rel} -> "${result.baseName}" (${result.questions.length} questions)`);
  allTests[result.baseName] = result.questions;
  successCount++;
}

console.log(`\nExtracted: ${successCount} tests, ${failCount} failures`);

// Generate TypeScript module
let ts = `// AUTO-GENERATED by scripts/extractQuestionData.js
// Do not edit manually. Re-run the script to update.
//
// Contains question text and options for Cambridge tests,
// used by the teacher answer review modal.

export interface QuestionOption {
  [key: string]: string; // A, B, C, D
}

export interface QuestionTable {
  headers: string[];
  rows: Array<{ label: string; values: string[] }>;
}

export interface QuestionData {
  number: number;
  prompt: string;
  options?: QuestionOption | null;
  table?: QuestionTable | null;
  image?: string | null;
}

/**
 * Map from QUIZ_BASE_NAME -> array of QuestionData.
 * For part-based tests, this contains ALL questions (both parts).
 * Use the question number + part split logic to filter.
 */
export const cambridgeQuestionBank: Record<string, QuestionData[]> = {\n`;

for (const [baseName, questions] of Object.entries(allTests)) {
  ts += `  ${JSON.stringify(baseName)}: ${JSON.stringify(questions, null, 2).split('\n').map((line, i) => i === 0 ? line : '  ' + line).join('\n')},\n\n`;
}

ts += `};\n\n`;

// Add helper function
ts += `/**
 * Look up questions for a given quiz_name (as stored in quiz_scores).
 * Handles part-based splitting automatically.
 */
export function getQuestionsForQuiz(quizName: string): QuestionData[] {
  if (!quizName) return [];

  // Direct match
  if (cambridgeQuestionBank[quizName]) {
    return cambridgeQuestionBank[quizName];
  }

  // Try stripping part suffix: "AS Chemistry Ch1 (Part 1)" -> "AS Chemistry Ch1"
  const partMatch = quizName.match(/^(.+?)\\s*\\(Part\\s+(\\d+)\\)$/i);
  if (partMatch) {
    const baseName = partMatch[1].trim();
    const part = parseInt(partMatch[2], 10);
    const allQuestions = cambridgeQuestionBank[baseName];
    if (allQuestions && allQuestions.length > 0) {
      const splitIndex = Math.ceil(allQuestions.length / 2);
      if (part === 1) {
        return allQuestions.slice(0, splitIndex);
      } else {
        return allQuestions.slice(splitIndex);
      }
    }
  }

  // Try fuzzy match by removing special chars
  const normalized = quizName.replace(/[^a-zA-Z0-9\\s]/g, '').toLowerCase().trim();
  for (const key of Object.keys(cambridgeQuestionBank)) {
    const keyNorm = key.replace(/[^a-zA-Z0-9\\s]/g, '').toLowerCase().trim();
    if (keyNorm === normalized || keyNorm.includes(normalized) || normalized.includes(keyNorm)) {
      return cambridgeQuestionBank[key];
    }
  }

  return [];
}
`;

fs.writeFileSync(OUTPUT_FILE, ts, 'utf-8');
console.log(`\nGenerated: ${OUTPUT_FILE}`);
console.log(`Total question bank entries: ${Object.keys(allTests).length}`);
