-- Canonicalise every legacy active English diagnostic taxonomy row using the
-- audited Brain Heist English Core Skill Registry v1 mapping.
-- Historical rows remain append-only and are superseded rather than mutated.

with legacy_map(old_primary,old_subskill,target_leaf_code) as (
  values
('academic vocabulary','distinguish epidemic and pandemic by geographical extent','eng.reading.vocabulary-context.context-clues'),
('academic vocabulary','interpret a colour-shade word from its instructional context','eng.reading.vocabulary-context.context-clues'),
('accessible communication','adapt emergency information for a multilingual audience','eng.writing.purpose-register.audience-purpose'),
('addition connectives','use furthermore to add supporting information','eng.use-of-english.connectives.addition-sequence'),
('adjective order','order a quality adjective before a colour adjective','eng.use-of-english.adjectives-adverbs.form-position'),
('adjective order','order multiple attributive adjectives naturally before a noun','eng.use-of-english.adjectives-adverbs.form-position'),
('adjectives','select a contextually appropriate adjective','eng.use-of-english.adjectives-adverbs.form-position'),
('analyzing aspect-dependent meaning','explain the opinion–consideration contrast with “think”','eng.use-of-english.verb-aspect.meaning-shift'),
('analyzing lexical meaning in context','distinguish possessive “have” from activity and experience meanings','eng.use-of-english.verb-aspect.meaning-shift'),
('anaphora','explain how repeated sentence openings emphasise imposed claims','eng.reading.language-effect.rhetorical'),
('applying meaning-based aspect choices','differentiate possessive “have” from activity-based “have”','eng.use-of-english.verb-aspect.meaning-shift'),
('applying non-continuous verb rules','use third-person singular simple-present “understands”','eng.use-of-english.verb-aspect.stative-dynamic'),
('argument and rhetoric','identify unwarranted generalization','eng.reading.argument-evaluation.reasoning'),
('argument and rhetoric','match evidence to a claim','eng.reading.argument-evaluation.claims-evidence'),
('argument and rhetoric','recognize ad hominem','eng.reading.argument-evaluation.reasoning'),
('argument and rhetoric','use concession and rebuttal','eng.reading.argument-evaluation.reasoning'),
('argument and source evaluation','evaluate generalisation and causation','eng.reading.argument-evaluation.reasoning'),
('argument and source evaluation','identify an unsupported assertion','eng.reading.argument-evaluation.claims-evidence'),
('argument structure','explain how evidence supports a central idea','eng.writing.argumentation.evidence-reasoning'),
('argument structure','select a conclusion that synthesizes evidence and recommendation','eng.writing.argumentation.evidence-reasoning'),
('article reference','use a for first mention and the for subsequent reference','eng.use-of-english.noun-phrase.articles-determiners'),
('article use','apply the zero-article convention to a general noun or institutional expression','eng.use-of-english.noun-phrase.articles-determiners'),
('audience and purpose','identify the intended audience of a notice','eng.reading.purpose-viewpoint.purpose-audience'),
('audience and purpose','identify the target audience of a campaign','eng.reading.purpose-viewpoint.purpose-audience'),
('author purpose','identify an explanatory purpose from paragraph content','eng.reading.purpose-viewpoint.purpose-audience'),
('be going to','form be going to questions about future plans','eng.use-of-english.verb-tense-time.future'),
('be going to','use be going to for a future plan or intention','eng.use-of-english.verb-tense-time.future'),
('be going to','use be going to for a prediction based on present evidence','eng.use-of-english.verb-tense-time.future'),
('causal claim evaluation','evaluate a route-delay claim using matched seasonal comparison data','eng.reading.argument-evaluation.reasoning'),
('causative have','diagnose an incorrect have something done construction','eng.use-of-english.voice-causative.causative'),
('causative have','form had + object + past participle for a past arranged service','eng.use-of-english.voice-causative.causative'),
('causative have','form have something done in the present','eng.use-of-english.voice-causative.causative'),
('causative have','form have/has + object + past participle for an arranged service','eng.use-of-english.voice-causative.causative'),
('causative have','form the progressive causative have something done','eng.use-of-english.voice-causative.causative'),
('causative have','form will have + object + past participle for a future arranged service','eng.use-of-english.voice-causative.causative'),
('character inference','infer a character''s distress from repeated reading and distracted behaviour','eng.reading.inference.attitude-feeling'),
('clause linking and participial forms','complete an adverbial clause with an appropriate linker or participial form','eng.use-of-english.nonfinite.participles'),
('close reading and interpretation','connect diction to tone','eng.reading.language-effect.diction-tone'),
('close reading and interpretation','infer symbolic meaning','eng.reading.language-effect.symbolism-imagery'),
('close reading and interpretation','interpret a sentence-length shift','eng.reading.language-effect.structural-effect'),
('close reading and interpretation','interpret self-correction','eng.reading.language-effect.structural-effect'),
('cohesion','select a transition that signals consequence','eng.writing.organization-cohesion.linking'),
('cohesion','select a transition that signals contrast','eng.writing.organization-cohesion.linking'),
('cohesion and connectives','select a connective that adds supporting information','eng.use-of-english.connectives.addition-sequence'),
('cohesion and connectives','select a connective that expresses cause, result, or consequence','eng.use-of-english.connectives.cause-effect'),
('cohesion and connectives','select a connective that introduces an example','eng.use-of-english.connectives.exemplification'),
('cohesion and connectives','select a connective that makes the relationship between clauses explicit','eng.use-of-english.connectives.addition-sequence'),
('cohesion and connectives','select a connective that organizes a sequence of ideas or steps','eng.use-of-english.connectives.addition-sequence'),
('cohesion and connectives','select a connective that signals a conclusion or synthesis','eng.use-of-english.connectives.addition-sequence'),
('cohesion and connectives','select a connective that signals an alternative or conditional outcome','eng.use-of-english.connectives.addition-sequence'),
('cohesion and connectives','select a connective that signals comparison or similarity','eng.use-of-english.connectives.addition-sequence'),
('cohesion and connectives','select a connective that signals contrast between ideas','eng.use-of-english.connectives.contrast-concession'),
('commas in lists','use commas to separate items in a list','eng.writing.mechanics.punctuation'),
('comparative adjectives','form short-adjective comparatives with -er','eng.use-of-english.adjectives-adverbs.comparison'),
('comparative adjectives','use a comparative adjective with than','eng.use-of-english.adjectives-adverbs.comparison'),
('comparative adjectives','use more with longer adjectives','eng.use-of-english.adjectives-adverbs.comparison'),
('comparative and source evaluation','assess methodological transparency','eng.reading.argument-evaluation.source-reliability'),
('comparative and source evaluation','identify confounding and missing controls','eng.reading.argument-evaluation.reasoning'),
('comparative and source evaluation','identify primary evidence','eng.reading.argument-evaluation.claims-evidence'),
('comparative and source evaluation','separate shared goals from implementation','eng.reading.argument-evaluation.compare-sources'),
('comparative and superlative adverbs','form and use a comparative adverb','eng.use-of-english.adjectives-adverbs.comparison'),
('comparative and superlative adverbs','form and use a superlative adverb','eng.use-of-english.adjectives-adverbs.comparison'),
('comparative and superlative spelling','change final -y to -i before adding -er or -est','eng.use-of-english.adjectives-adverbs.comparison'),
('comparative and superlative spelling','double the final consonant before -er or -est in short cvc adjectives','eng.use-of-english.adjectives-adverbs.comparison'),
('comparative contrast conjunction use','complete a comparison with whereas','eng.use-of-english.connectives.contrast-concession'),
('comparative contrast conjunction use','identify whereas connecting two place-based contrasts','eng.use-of-english.connectives.contrast-concession'),
('comparative quantifiers','distinguish comparative quantifiers for countable and uncountable nouns','eng.use-of-english.noun-phrase.quantifiers'),
('comparative quantifiers','use fewer with countable plural nouns','eng.use-of-english.noun-phrase.quantifiers'),
('comparative quantifiers','use least for the smallest uncountable quantity','eng.use-of-english.noun-phrase.quantifiers'),
('comparative quantifiers','use less with uncountable nouns','eng.use-of-english.noun-phrase.quantifiers'),
('comparison of contrast conjunctions','evaluate whether whereas preserves an although relationship','eng.use-of-english.connectives.contrast-concession'),
('comparison structures','use as ... as to express equality','eng.use-of-english.adjectives-adverbs.comparison'),
('comparison structures','use the ... the ... correlative comparative structure','eng.use-of-english.adjectives-adverbs.comparison'),
('compound adjective hyphenation','hyphenate a compound modifier before a noun','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjective hyphenation','identify a correctly hyphenated compound modifier','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjectives','do not hyphenate an -ly adverb followed by a participle','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjectives','hyphenate a compound modifier used before a noun','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjectives','hyphenate number-based compound modifiers and keep the unit noun singular','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjectives','identify an ill-formed or redundant compound adjective','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjectives','select a contextually appropriate compound adjective','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjectives','use a hyphenated compound adjective such as sky-high before a noun','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound adjectives','use an -ing compound adjective such as mouth-watering before a noun','eng.use-of-english.adjectives-adverbs.compound-modifiers'),
('compound sentences','identify a compound sentence formed from two independent clauses joined by a coordinating conjunction','eng.writing.sentence-control.variety'),
('concessive conjunction meaning','reject an incorrect restriction on although','eng.use-of-english.connectives.contrast-concession'),
('concessive conjunction use','complete a sentence with although to show unexpected contrast','eng.use-of-english.connectives.contrast-concession'),
('concessive conjunction use','select although for contrast within one situation','eng.use-of-english.connectives.contrast-concession'),
('concessive conjunction use','select although when an outcome defies expectation','eng.use-of-english.connectives.contrast-concession'),
('conjunctions (when - while - after - before)','select after to show that one event followed another','eng.use-of-english.clauses-subordination.adverbial'),
('conjunctions (when - while - after - before)','select while for an ongoing action interrupted by an event','eng.use-of-english.clauses-subordination.adverbial'),
('contrast connectives','use conversely to introduce an opposing perspective','eng.use-of-english.connectives.addition-sequence'),
('contrast connectives','use however to signal contrast','eng.use-of-english.connectives.contrast-concession'),
('contrasting habitual and current actions','select simple and continuous forms for two different time meanings','eng.use-of-english.verb-aspect.habitual-temporary'),
('countable and uncountable nouns','apply uncountable-noun conventions to homework','eng.use-of-english.noun-phrase.countability-number'),
('definite article: the','use the for a specific identifiable reference','eng.use-of-english.noun-phrase.articles-determiners'),
('definite article: the','use the with a unique reference','eng.use-of-english.noun-phrase.articles-determiners'),
('definite article: the','use the with mountain ranges','eng.use-of-english.noun-phrase.articles-determiners'),
('dependent prepositions following verbs','select the dependent preposition used with compare','eng.use-of-english.prepositions-patterns.verb-dependent'),
('distinguishing general and temporary meanings','identify simple present used for a general preference','eng.use-of-english.verb-aspect.habitual-temporary'),
('do and does for emphasis','use do to emphasize a present simple affirmative','eng.use-of-english.questions-negation.emphasis'),
('editing aspect for usual characteristics','replace continuous “be” with simple “be” for a usual trait','eng.use-of-english.verb-aspect.habitual-temporary'),
('editing comparative contrasts','replace although with whereas in a two-subject comparison','eng.use-of-english.connectives.contrast-concession'),
('editing for concision','edit a sentence to remove redundancy','eng.writing.planning-revision.revise-content'),
('emphatic do','form emphasis with do before a base verb','eng.use-of-english.questions-negation.emphasis'),
('emphatic do','keep the main verb in base form after do, does, or did','eng.use-of-english.questions-negation.emphasis'),
('emphatic do','use did + base verb for affirmative past emphasis','eng.use-of-english.questions-negation.emphasis'),
('emphatic do','use do or does + base verb for affirmative emphasis','eng.use-of-english.questions-negation.emphasis'),
('evidence selection','select quantitative evidence relevant to a participation claim','eng.writing.argumentation.evidence-reasoning'),
('evidence selection','select relevant evidence for a claim','eng.writing.argumentation.evidence-reasoning'),
('evidence-based inference','select behavioral evidence that contradicts spoken words','eng.reading.inference.unstated-meaning'),
('evidence-based inference','select evidence that establishes narrator distrust','eng.reading.inference.attitude-feeling'),
('explaining aspect choice','justify continuous “look” using temporary and contrastive meaning','eng.use-of-english.verb-aspect.habitual-temporary'),
('explicit information retrieval','retrieve an explicit meeting time from a notice','eng.reading.explicit-information.locate-detail'),
('explicit information retrieval','retrieve an explicit time from a notice','eng.reading.explicit-information.locate-detail'),
('expressing temporary appearance','select continuous “look” to highlight an appearance that differs from usual','eng.use-of-english.verb-aspect.habitual-temporary'),
('expressing temporary behaviour','select present continuous “be” for behaviour occurring now','eng.use-of-english.verb-aspect.habitual-temporary'),
('figurative language','explain the emotional effect of figurative description','eng.reading.language-effect.figurative'),
('figurative language','identify a metaphor','eng.reading.language-effect.figurative'),
('figurative language','identify personification','eng.reading.language-effect.figurative'),
('figurative language','identify personification in a clause','eng.reading.language-effect.figurative'),
('figurative language','interpret a metaphor as suggesting navigational confusion','eng.reading.language-effect.figurative'),
('figurative language','interpret the image and effect created by a metaphor','eng.reading.language-effect.figurative'),
('figurative language','interpret the image created by a simile','eng.reading.language-effect.figurative'),
('figurative language','interpret the visual effect of a metaphor','eng.reading.language-effect.figurative'),
('figurative language: metaphor','identify a metaphor as a direct comparison without like or as','eng.reading.language-effect.figurative'),
('first conditional','form the first conditional with if + present simple and will + base verb','eng.use-of-english.conditionals.real'),
('forming present continuous verbs','construct two first-person present continuous verb phrases','eng.use-of-english.verb-tense-time.present'),
('future continuous','diagnose an incorrect future-continuous form','eng.use-of-english.verb-tense-time.future'),
('future continuous','distinguish a future event from an action in progress at a future time','eng.use-of-english.verb-tense-time.future'),
('future continuous','form future-continuous questions','eng.use-of-english.verb-tense-time.future'),
('future continuous','form negative future-continuous questions','eng.use-of-english.verb-tense-time.future'),
('future continuous','form the future continuous with will be + -ing','eng.use-of-english.verb-tense-time.future'),
('future continuous','form the negative future continuous with will not be + -ing','eng.use-of-english.verb-tense-time.future'),
('future continuous','use will be + -ing for an action in progress at a future time','eng.use-of-english.verb-tense-time.future'),
('future continuous tense','form the future continuous for an action in progress at a future time','eng.use-of-english.verb-tense-time.future'),
('future passive','form the future passive with will be + past participle','eng.use-of-english.voice-causative.passive-range'),
('future passive','form the negative future passive with won’t be + past participle','eng.use-of-english.voice-causative.passive-range'),
('future passive','transform an active will-future sentence into the future passive','eng.use-of-english.voice-causative.passive-range'),
('future tense','form a future question with will + subject + base verb','eng.use-of-english.verb-tense-time.future'),
('future tense','form an affirmative future sentence with will + base verb','eng.use-of-english.verb-tense-time.future'),
('future tense','form the negative future with will not + base verb','eng.use-of-english.verb-tense-time.future'),
('future tense','identify a future action expressed with will','eng.use-of-english.verb-tense-time.future'),
('future tense','select the future form from a future-time context','eng.use-of-english.verb-tense-time.future'),
('future tense','use the base verb after will','eng.use-of-english.verb-tense-time.future'),
('grammar and cohesion','apply subject–verb agreement','eng.use-of-english.agreement-reference.subject-verb'),
('grammar and cohesion','introduce an explanation with a colon','eng.writing.mechanics.punctuation'),
('grammar and cohesion','join independent clauses with a semicolon','eng.writing.mechanics.punctuation'),
('grammar and cohesion','maintain consistent verb tense','eng.writing.grammar-control.tense-consistency'),
('grammar and cohesion','punctuate a non-essential relative clause','eng.writing.mechanics.punctuation'),
('grammar and cohesion','resolve ambiguous reference','eng.use-of-english.agreement-reference.pronoun'),
('grammar and cohesion','revise a sentence to clarify pronoun reference','eng.use-of-english.agreement-reference.pronoun'),
('grammar and cohesion','select a result connector','eng.use-of-english.connectives.cause-effect'),
('grammar and punctuation','apply subject-verb agreement','eng.use-of-english.agreement-reference.subject-verb'),
('grammar and punctuation','identify a sentence in the past tense','eng.use-of-english.verb-tense-time.past'),
('grammar and punctuation','punctuate direct speech correctly','eng.writing.mechanics.punctuation'),
('grammar and punctuation','select a causal conjunction to connect ideas','eng.use-of-english.connectives.cause-effect'),
('grammar and sentence clarity','apply subject-verb agreement with an intervening phrase','eng.use-of-english.agreement-reference.subject-verb'),
('grammar and sentence clarity','combine clauses using a subordinating conjunction','eng.writing.sentence-control.subordination'),
('grammar and sentence clarity','identify an ambiguous pronoun reference','eng.use-of-english.agreement-reference.pronoun'),
('grammar and sentence clarity','punctuate direct speech correctly','eng.writing.mechanics.punctuation'),
('grammar and sentence clarity','revise a passive construction to remove a dangling modifier','eng.writing.planning-revision.edit-language'),
('grammar and sentence clarity','select a causal conjunction','eng.use-of-english.connectives.cause-effect'),
('grammar and voice','use active voice to make the responsible agent explicit','eng.use-of-english.voice-causative.passive'),
('grammatical use of although','identify a correctly formed concessive sentence','eng.use-of-english.connectives.contrast-concession'),
('has/have/had something done','select the past causative have construction','eng.use-of-english.voice-causative.causative'),
('have to, don''t have to, must, mustn''t','select have to for an external requirement or deadline','eng.use-of-english.modality.obligation-prohibition'),
('have to, don''t have to, must, mustn''t','select must for a strong rule or obligation','eng.use-of-english.modality.obligation-prohibition'),
('indefinite articles: a / an','choose a or an according to the following sound','eng.use-of-english.noun-phrase.articles-determiners'),
('indefinite articles: a / an','use a for a first-mentioned singular count noun','eng.use-of-english.noun-phrase.articles-determiners'),
('inference and evidence','compare statement and behaviour','eng.reading.inference.unstated-meaning'),
('inference and evidence','match evidence to an inference','eng.reading.inference.unstated-meaning'),
('inference and evidence','recognise ironic qualification','eng.reading.inference.attitude-feeling'),
('information navigation','select headings and sections for rapid information retrieval','eng.reading.strategy-selection.select-relevant'),
('information navigation','use a heading to locate specific information','eng.reading.strategy-selection.select-relevant'),
('informational text comprehension','explain a stated cause, method, or consequence in an informational text','eng.reading.explicit-information.identify-fact'),
('informational text comprehension','interpret an explanation or term from an informational text about colour vision','eng.reading.explicit-information.identify-fact'),
('informational text comprehension','retrieve an explicitly stated fact from an informational text about colour vision','eng.reading.explicit-information.locate-detail'),
('informational text comprehension','retrieve an explicitly stated fact from an informational text about disease','eng.reading.explicit-information.locate-detail'),
('informational text: cause and effect','identify a stated cause for an observed effect','eng.reading.connections.logical-relations'),
('informational text: explicit detail','retrieve an explicitly stated factual detail','eng.reading.explicit-information.locate-detail'),
('informational text: explicit detail','retrieve an explicitly stated numerical detail','eng.reading.explicit-information.locate-detail'),
('instruction design','select numbered imperative actions for scannable safety instructions','eng.writing.purpose-register.text-conventions'),
('integrating aspect choices in context','coordinate simple “be,” continuous “be,” and simple “understand” in a passage','eng.use-of-english.verb-aspect.habitual-temporary'),
('interpretation of whereas','explain the contrast relationship signaled by whereas','eng.use-of-english.connectives.contrast-concession'),
('interpretation of whereas','recognize a two-item comparison introduced by whereas','eng.use-of-english.connectives.contrast-concession'),
('interpreting aspect-dependent verb meaning','distinguish opinion from active consideration with “think”','eng.use-of-english.verb-aspect.meaning-shift'),
('interpreting temporary behaviour','infer temporary meaning from continuous “be” and context markers','eng.use-of-english.verb-aspect.habitual-temporary'),
('irregular comparative and superlative forms','use an irregular comparative or superlative form','eng.use-of-english.adjectives-adverbs.comparison'),
('irregular verbs','distinguish an irregular verb’s past simple and past participle forms','eng.use-of-english.verb-tense-time.regular-irregular'),
('irregular verbs','recall the past participle of buy: bought','eng.use-of-english.verb-tense-time.regular-irregular'),
('irregular verbs','recall the past simple form of write: wrote','eng.use-of-english.verb-tense-time.regular-irregular'),
('irregular verbs','use the correct irregular past participle','eng.use-of-english.verb-tense-time.regular-irregular'),
('irregular verbs','use the correct irregular past-simple form','eng.use-of-english.verb-tense-time.regular-irregular'),
('justification of conjunction choice','select and justify whereas for a direct comparison','eng.use-of-english.connectives.contrast-concession'),
('modals: obligation, prohibition and necessity','distinguish mustn’t from don’t have to','eng.use-of-english.modality.obligation-prohibition'),
('modals: obligation, prohibition and necessity','distinguish obligation, prohibition, and lack of necessity','eng.use-of-english.modality.obligation-prohibition'),
('modals: obligation, prohibition and necessity','form have to questions with do + subject + have to','eng.use-of-english.modality.obligation-prohibition'),
('modals: obligation, prohibition and necessity','use a base verb without to after mustn’t','eng.use-of-english.modality.obligation-prohibition'),
('modals: obligation, prohibition and necessity','use don’t/doesn’t have to for lack of necessity','eng.use-of-english.modality.obligation-prohibition'),
('modals: obligation, prohibition and necessity','use have to / has to for external obligation','eng.use-of-english.modality.obligation-prohibition'),
('modals: obligation, prohibition and necessity','use must for strong obligation or a firm rule','eng.use-of-english.modality.obligation-prohibition'),
('modals: obligation, prohibition and necessity','use mustn’t for prohibition','eng.use-of-english.modality.obligation-prohibition'),
('multimodal inference','infer a preceding event from a visual sequence','eng.reading.multimodal.visual-inference'),
('multimodal inference','infer a preceding event from visual clues','eng.reading.multimodal.visual-inference'),
('multimodal inference','infer an action from a visual sequence','eng.reading.multimodal.visual-inference'),
('multimodal inference','infer an event from visual clues','eng.reading.multimodal.visual-inference'),
('narrative structure','explain how revealing the ending first shifts suspense to causes','eng.reading.language-effect.structural-effect'),
('noun modifiers','recognize attributive noun modifier use','eng.use-of-english.noun-phrase.possession'),
('noun plurals','add -es to nouns ending in -s: bus → buses','eng.use-of-english.noun-phrase.countability-number'),
('participle adjectives','select a grammatically correct participle adjectives construction in context','eng.use-of-english.adjectives-adverbs.participle-adjectives'),
('participle adjectives','select an -ing adjective for the source of a feeling','eng.use-of-english.adjectives-adverbs.participle-adjectives'),
('participle adjectives','use an -ed adjective for the person experiencing a feeling','eng.use-of-english.adjectives-adverbs.participle-adjectives'),
('participle adjectives','use an -ed adjective for the person or thing experiencing a feeling','eng.use-of-english.adjectives-adverbs.participle-adjectives'),
('participle adjectives','use an -ing adjective for the cause of a feeling','eng.use-of-english.adjectives-adverbs.participle-adjectives'),
('participle adjectives','use an -ing adjective for the cause or source of a feeling','eng.use-of-english.adjectives-adverbs.participle-adjectives'),
('parts of speech','identify a noun as a word naming a person, place, thing, or idea','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify a noun form in sentence context','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify a noun in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify an adjective in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify an adverb in context','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the adjective function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the adverb function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the conjunction function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the interjection function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the noun function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the preposition function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the pronoun function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the verb function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','identify the word class function of a word in a sentence','eng.use-of-english.word-formation.word-classes'),
('parts of speech','recognize the definition of an adjective','eng.use-of-english.word-formation.word-classes'),
('passive infinitive','form have to be + past participle','eng.use-of-english.nonfinite.passive-infinitive'),
('passive infinitive','form the passive infinitive with to be + past participle','eng.use-of-english.nonfinite.passive-infinitive'),
('passive voice','recall the be-plus-past-participle structure of the passive voice','eng.use-of-english.voice-causative.passive-range'),
('passive voice','transform an active sentence into the contextually appropriate passive form','eng.use-of-english.voice-causative.passive-range'),
('past continuous','combine an ongoing background action with a shorter past event','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','diagnose an inconsistent past continuous construction','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','form past-continuous questions with was/were + subject + -ing','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','form the negative past continuous in context','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','form the negative past continuous with was/were not + -ing','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','form the past continuous with was/were + -ing','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','select past continuous for an action in progress at a specific past time','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','use past continuous for a background action interrupted by past simple','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','use past continuous for an action in progress around a past event','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','use past continuous with while for an action in progress','eng.use-of-english.verb-aspect.simple-progressive'),
('past continuous','use the past continuous for an action in progress at a past time','eng.use-of-english.verb-aspect.simple-progressive'),
('past modals','interpret the meaning of need not have plus past participle','eng.use-of-english.modality.deduction-past'),
('past modals','use a past participle after modal + have','eng.use-of-english.modality.deduction-past'),
('past modals: criticism and regret','use should have / shouldn’t have for past criticism or regret','eng.use-of-english.modality.deduction-past'),
('past modals: deduction','use can’t have for a past conclusion judged impossible','eng.use-of-english.modality.deduction-past'),
('past modals: deduction','use must have for a strong deduction about the past','eng.use-of-english.modality.deduction-past'),
('past modals: possibility','use may have / might have for past possibility','eng.use-of-english.modality.possibility-probability'),
('past modals: possibility','use may have for a possible past explanation','eng.use-of-english.modality.possibility-probability'),
('past modals: possibility','use might have for an uncertain possibility about the past','eng.use-of-english.modality.possibility-probability'),
('past modals: possibility','use might not have for an uncertain negative past possibility','eng.use-of-english.modality.possibility-probability'),
('past modals: possibility','use might not have for an uncertain negative possibility about the past','eng.use-of-english.modality.possibility-probability'),
('past modals: unnecessary completed action','use needn’t have for an unnecessary action that was completed','eng.use-of-english.modality.deduction-past'),
('past modals: unrealized possibility','use could have for an unrealized past possibility','eng.use-of-english.modality.deduction-past'),
('past necessity','interpret didn’t need to as lack of past necessity','eng.use-of-english.modality.obligation-prohibition'),
('past perfect active','form past-perfect-active questions','eng.use-of-english.verb-tense-time.perfect'),
('past perfect active','form the past perfect active with had + past participle','eng.use-of-english.verb-tense-time.perfect'),
('past perfect passive','form past perfect passive questions','eng.use-of-english.voice-causative.passive-range'),
('past perfect passive','form the past perfect passive with had been + past participle','eng.use-of-english.voice-causative.passive-range'),
('past perfect passive','transform an active past-perfect sentence into the passive','eng.use-of-english.voice-causative.passive-range'),
('past perfect simple (active and passive)','convert a past perfect passive sentence to an equivalent active form','eng.use-of-english.voice-causative.passive-range'),
('past simple passive','form a question in the past simple passive with was/were + past participle','eng.use-of-english.voice-causative.passive-range'),
('past simple passive','form the past simple passive with was/were + past participle','eng.use-of-english.voice-causative.passive-range'),
('past simple passive','transform an active past-simple sentence into the passive','eng.use-of-english.voice-causative.passive-range'),
('personification','interpret personification as making a deadline feel slowly threatening','eng.reading.language-effect.figurative'),
('persuasive language','identify an appeal to shared community benefit','eng.writing.argumentation.persuasion'),
('placement of although clauses','recognize two valid positions for an although clause','eng.use-of-english.connectives.contrast-concession'),
('precise vocabulary','select a verb that conveys relaxed movement','eng.reading.vocabulary-context.nuance'),
('precise vocabulary','select a verb with the strongest force connotation','eng.reading.vocabulary-context.nuance'),
('present and past simple passive','convert a present simple active sentence to the passive','eng.use-of-english.voice-causative.passive-range'),
('present and past simple passive','form the past simple passive with a plural subject','eng.use-of-english.voice-causative.passive-range'),
('present and past simple passive','identify the auxiliary verb used to form the passive','eng.use-of-english.voice-causative.passive-range'),
('present and past simple passive','select a grammatically correct present and past simple passive construction in context','eng.use-of-english.voice-causative.passive-range'),
('present continuous for future arrangements','use present continuous for a fixed future arrangement','eng.use-of-english.verb-tense-time.future'),
('present perfect active','form present perfect active questions with have/has + subject + past participle','eng.use-of-english.verb-tense-time.perfect'),
('present perfect active','form present-perfect-active questions','eng.use-of-english.verb-tense-time.perfect'),
('present perfect active','form the present perfect active with have/has + past participle','eng.use-of-english.verb-tense-time.perfect'),
('present perfect active and passive','match active and passive present-perfect sentences with equivalent meaning','eng.use-of-english.voice-causative.passive-range'),
('present perfect continuous','form a how long question with the present perfect continuous','eng.use-of-english.verb-tense-time.perfect'),
('present perfect continuous','form how long questions in the present perfect continuous','eng.use-of-english.verb-tense-time.perfect'),
('present perfect continuous','form present-perfect-continuous questions with have/has + been + -ing','eng.use-of-english.verb-tense-time.perfect'),
('present perfect continuous','form questions with have/has + been + -ing','eng.use-of-english.verb-tense-time.perfect'),
('present perfect continuous','form the negative present perfect continuous','eng.use-of-english.verb-tense-time.perfect'),
('present perfect continuous','use have/has been + -ing for continuing or recent activity','eng.use-of-english.verb-tense-time.perfect'),
('present perfect continuous','use present perfect continuous for recent repeated or ongoing activity','eng.use-of-english.verb-tense-time.perfect'),
('present perfect passive','form present perfect passive questions with has/have + subject + been','eng.use-of-english.voice-causative.passive-range'),
('present perfect passive','form present-perfect-passive questions','eng.use-of-english.voice-causative.passive-range'),
('present perfect passive','form the negative present perfect passive','eng.use-of-english.voice-causative.passive-range'),
('present perfect passive','form the present perfect passive with has/have been + past participle','eng.use-of-english.voice-causative.passive-range'),
('present perfect passive','form the present perfect passive with have/has been + past participle','eng.use-of-english.voice-causative.passive-range'),
('present simple for timetables','use present simple for a fixed timetable or schedule','eng.use-of-english.verb-tense-time.future'),
('present simple for timetables','use present simple for fixed future schedules','eng.use-of-english.verb-tense-time.future'),
('present simple passive','form present-simple-passive questions','eng.use-of-english.voice-causative.passive-range'),
('present simple passive','form the present simple passive with am/is/are + past participle','eng.use-of-english.voice-causative.passive-range'),
('purpose and audience','combine evidence and call to action','eng.writing.purpose-register.audience-purpose'),
('purpose and audience','open a formal request','eng.writing.purpose-register.audience-purpose'),
('purpose and audience','present a balanced position','eng.writing.purpose-register.audience-purpose'),
('question marks','end a direct question with a question mark','eng.writing.mechanics.punctuation'),
('recognising present continuous structure','identify the auxiliary and -ing form as one verb phrase','eng.use-of-english.verb-tense-time.present'),
('register and tone','select a clear and direct tone for safety instructions','eng.writing.purpose-register.register-tone'),
('register and tone','select a formal request for a school principal','eng.writing.purpose-register.register-tone'),
('register and tone','select a polite request for the audience','eng.writing.purpose-register.register-tone'),
('register and tone','select an appropriately formal report opening','eng.writing.purpose-register.register-tone'),
('register and tone','select appropriately polite language for a teacher','eng.writing.purpose-register.register-tone'),
('regular verb spelling','add -d to a regular verb ending in -e','eng.use-of-english.verb-tense-time.regular-irregular'),
('regular verb spelling','add -ed to form a regular past-simple verb','eng.use-of-english.verb-tense-time.regular-irregular'),
('regular verb spelling','double the final consonant before -ed in a short cvc verb','eng.use-of-english.verb-tense-time.regular-irregular'),
('relative pronouns','use that in a defining relative clause','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use when for a time antecedent','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use where for a place antecedent','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use which for a thing or non-human antecedent','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use who for a person functioning as the relative-clause subject','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use who for a person functioning as the subject of a relative clause','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use whom for a person functioning as the relative-clause object','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use whose for possession and that for a defining relative clause','eng.use-of-english.agreement-reference.relative-pronouns'),
('relative pronouns','use whose to express possession in a relative clause','eng.use-of-english.agreement-reference.relative-pronouns'),
('reported questions','backshift past simple to past perfect in a reported question','eng.use-of-english.reported-speech.questions-commands'),
('reported speech','adjust pronouns to match the reporting perspective','eng.use-of-english.reported-speech.reference'),
('reported speech','apply tense backshift and reference changes in reported speech','eng.use-of-english.reported-speech.reference'),
('reported speech','backshift can/can’t to could/couldn’t in reported speech','eng.use-of-english.reported-speech.reference'),
('reported speech','backshift present continuous to past continuous','eng.use-of-english.reported-speech.reference'),
('reported speech','backshift present perfect continuous to past perfect continuous','eng.use-of-english.reported-speech.reference'),
('reported speech','backshift present tense to past in reported speech','eng.use-of-english.reported-speech.reference'),
('reported speech','backshift to the past perfect where required','eng.use-of-english.reported-speech.reference'),
('reported speech','backshift will to would in reported speech','eng.use-of-english.reported-speech.reference'),
('reported speech','change here to there when reporting from a different place','eng.use-of-english.reported-speech.statements'),
('reported speech','change yesterday to the day before in reported speech','eng.use-of-english.reported-speech.statements'),
('reported speech','diagnose incorrect question word order in reported speech','eng.use-of-english.reported-speech.questions-commands'),
('reported speech','keep present tense for a still-true general fact','eng.use-of-english.reported-speech.statements'),
('reported speech','report commands with tell + object + to-infinitive','eng.use-of-english.reported-speech.questions-commands'),
('reported speech','report negative advice with tell + object + not to-infinitive','eng.use-of-english.reported-speech.statements'),
('reported speech','report wh-questions using statement word order','eng.use-of-english.reported-speech.questions-commands'),
('reported speech','report yes/no questions with if/whether and statement word order','eng.use-of-english.reported-speech.questions-commands'),
('reported speech','use tell with an object and say without a direct object','eng.use-of-english.reported-speech.statements'),
('reported speech','use warn + object + not to-infinitive for a reported warning','eng.use-of-english.reported-speech.statements'),
('research and synthesis','combine benefit and limitation','eng.writing.source-use.synthesis'),
('research and synthesis','distinguish outcomes and study strength','eng.writing.source-use.synthesis'),
('research and synthesis','link evidence to a claim','eng.writing.source-use.integrate-evidence'),
('research and synthesis','paraphrase with attribution','eng.writing.source-use.paraphrase-attribution'),
('rewriting contrast with although','replace but with an although clause','eng.use-of-english.connectives.contrast-concession'),
('selecting verb aspect from context','identify a present continuous form describing an activity in progress','eng.use-of-english.verb-aspect.simple-progressive'),
('sentence combination with whereas','join two contrasting descriptions using whereas','eng.use-of-english.connectives.contrast-concession'),
('sentence structure','explain how an abrupt final fragment contrasts with sustained movement','eng.reading.language-effect.structural-effect'),
('source bias','evaluate manufacturer-selected testimonials for selection bias and lack of independent testing','eng.reading.argument-evaluation.source-reliability'),
('source evaluation','evaluate an absolute claim by checking credible supporting evidence','eng.reading.argument-evaluation.source-reliability'),
('source evaluation','evaluate an unsupported health claim by seeking reliable evidence','eng.reading.argument-evaluation.source-reliability'),
('source evaluation','question an unsupported advertising claim and seek reliable evidence','eng.reading.argument-evaluation.source-reliability'),
('subject-verb agreement','agree with a monetary amount treated as a single unit','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','agree with a plural antecedent in a relative clause','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','agree with a singular head noun before an of-phrase','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','agree with a singular head noun in an of-phrase','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','agree with the singular indefinite pronoun each','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','agree with the singular indefinite pronoun everyone','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','agree with the singular subject noun mathematics','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','apply proximity agreement with either-or','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','diagnose a plural-subject singular-verb agreement error','eng.use-of-english.agreement-reference.subject-verb'),
('subject-verb agreement','select the third-person singular present simple verb form','eng.use-of-english.agreement-reference.subject-verb'),
('subject–verb agreement','apply third-person singular -s in the present simple','eng.use-of-english.agreement-reference.subject-verb'),
('subject–verb agreement','use the base present form with a plural subject','eng.use-of-english.agreement-reference.subject-verb'),
('subject–verb agreement','use there are with a plural noun','eng.use-of-english.agreement-reference.subject-verb'),
('subject–verb agreement','use there is with a singular noun','eng.use-of-english.agreement-reference.subject-verb'),
('superlative adjective spelling','change final -y to -i before adding -est','eng.use-of-english.adjectives-adverbs.comparison'),
('superlative adjectives','form short-adjective superlatives with -est','eng.use-of-english.adjectives-adverbs.comparison'),
('superlative adjectives','use most with longer adjectives','eng.use-of-english.adjectives-adverbs.comparison'),
('superlative adjectives','use the + -est for short-adjective superlatives','eng.use-of-english.adjectives-adverbs.comparison'),
('textual inference','infer a character''s emotion from behavior','eng.reading.inference.unstated-meaning'),
('textual inference','infer an expected departure from behavioral details','eng.reading.inference.unstated-meaning'),
('textual inference','infer an expected event from a character''s preparations','eng.reading.inference.unstated-meaning'),
('textual inference','infer uncertainty from a sequence of actions','eng.reading.inference.unstated-meaning'),
('textual inference','infer weather from a character''s actions','eng.reading.inference.unstated-meaning'),
('the passive infinitive','complete a sentence with a contextually appropriate the passive infinitive form','eng.use-of-english.nonfinite.passive-infinitive'),
('the passive infinitive','diagnose an incorrect the passive infinitive construction','eng.use-of-english.nonfinite.passive-infinitive'),
('theme interpretation','infer a theme from recurring symbolic contrast','eng.reading.language-effect.symbolism-imagery'),
('third conditional','apply if + past perfect and would have + past participle','eng.use-of-english.conditionals.past-unreal'),
('third conditional','diagnose an incorrect third-conditional form','eng.use-of-english.conditionals.past-unreal'),
('third conditional','form a negative third conditional result clause','eng.use-of-english.conditionals.past-unreal'),
('third conditional','form the if-clause with the past perfect','eng.use-of-english.conditionals.past-unreal'),
('third conditional','form the result clause with would have + past participle','eng.use-of-english.conditionals.past-unreal'),
('time conjunctions','use after to show sequence of events','eng.use-of-english.clauses-subordination.adverbial'),
('time conjunctions','use after to show that one event follows another','eng.use-of-english.clauses-subordination.adverbial'),
('time conjunctions','use before to show sequence of events','eng.use-of-english.clauses-subordination.adverbial'),
('time conjunctions','use before to show that one event happens earlier than another','eng.use-of-english.clauses-subordination.adverbial'),
('time conjunctions','use when for a time or triggering event','eng.use-of-english.clauses-subordination.adverbial'),
('time conjunctions','use while for an ongoing or simultaneous action','eng.use-of-english.clauses-subordination.adverbial'),
('time conjunctions','use while to link simultaneous actions','eng.use-of-english.clauses-subordination.adverbial'),
('use of contrast conjunctions','recall the function of although','eng.use-of-english.connectives.contrast-concession'),
('use of contrast conjunctions','recall the shared function of while and whereas','eng.use-of-english.connectives.contrast-concession'),
('use of while for contrast','recognize the contrast function of while','eng.use-of-english.connectives.contrast-concession'),
('using non-continuous verb forms','use simple-present “understand” for a current mental state','eng.use-of-english.verb-aspect.stative-dynamic'),
('verb-dependent prepositions','apply the required verb + preposition pattern','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use agree + with','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use approve + of','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use believe + in','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use belong + to','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use compare + with','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use concentrate + on','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use depend + on','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use die + of for a disease or cause','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use introduce + object + to','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use listen + to','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use protect + object + from','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use rely + on','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use save + object + from','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use specialise + in','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use succeed + in','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verb-dependent prepositions','use suffer + from','eng.use-of-english.prepositions-patterns.verb-dependent'),
('verbs tenses regular and irregular','form the past simple of a regular verb ending in consonant y','eng.use-of-english.verb-tense-time.regular-irregular'),
('verbs tenses regular and irregular','select a grammatically correct verbs tenses regular and irregular construction in context','eng.use-of-english.verb-tense-time.regular-irregular'),
('vocabulary and language effect','select a word at the correct point on an intensity scale','eng.reading.vocabulary-context.nuance'),
('vocabulary in context','derive the meaning of reluctant from context','eng.reading.vocabulary-context.context-clues'),
('vocabulary in context','derive word meaning from sentence context','eng.reading.vocabulary-context.context-clues'),
('vocabulary in context','identify a synonym in context','eng.reading.vocabulary-context.context-clues'),
('vocabulary in context','select a precise verb for speed','eng.reading.vocabulary-context.context-clues'),
('vocabulary in context','select an adjective at the correct point on an intensity scale','eng.reading.vocabulary-context.context-clues'),
('will future','form the negative future with will not + base verb','eng.use-of-english.verb-tense-time.future'),
('will future','use will for a general future prediction','eng.use-of-english.verb-tense-time.future'),
('will future','use will for a spontaneous offer or decision','eng.use-of-english.verb-tense-time.future'),
('word morphology','interpret the meaning of a prefix','eng.use-of-english.word-formation.affixes'),
('writing craft and control','correct modifier attachment','eng.writing.planning-revision.edit-language'),
('writing craft and control','join independent clauses','eng.writing.content-development.develop-ideas'),
('writing craft and control','make a qualified claim','eng.writing.argumentation.claim-position'),
('writing craft and control','signal contrast','eng.writing.organization-cohesion.linking'),
('writing organization','place an instruction first in a logical sequence','eng.writing.organization-cohesion.logical-order'),
('writing organization','place evidence after a claim in a paragraph structure','eng.writing.organization-cohesion.paragraphing'),
('writing organization','place supporting evidence in a paragraph plan','eng.writing.organization-cohesion.paragraphing'),
('writing organization','select a coherent story ending','eng.writing.organization-cohesion.logical-order'),
('writing organization','select a focused topic sentence','eng.writing.organization-cohesion.logical-order'),
('writing organization','select an engaging narrative opening','eng.writing.organization-cohesion.logical-order'),
('writing organization','sequence a procedural event from visual information','eng.writing.organization-cohesion.logical-order'),
('writing organization','sequence procedural instructions','eng.writing.organization-cohesion.logical-order'),
('zero article','use no article with an uncountable noun in a general sense','eng.use-of-english.noun-phrase.articles-determiners'),
('zero article','use no article with names of languages','eng.use-of-english.noun-phrase.articles-determiners'),
('zero article','use no article with names of meals','eng.use-of-english.noun-phrase.articles-determiners')
),
legacy as (
  select t.*,
         lower(trim(t.primary_skill_name)) old_primary,
         lower(trim(t.atomic_subskill_name)) old_subskill
  from private.active_verified_question_diagnostic_taxonomy t
  join public.questions q on q.id=t.question_id
  join public.academic_subjects subj on subj.id=q.academic_subject_id
  where lower(trim(coalesce(subj.code,subj.name)))='english'
    and not exists (
      select 1
      from public.academic_skill_registry_nodes leaf
      join public.academic_skill_registry_nodes skill on skill.id=leaf.parent_id
      join public.academic_skill_registry_versions v on v.id=leaf.registry_version_id
      where v.code='bh-english-core-v1'
        and skill.code=t.primary_skill_code
        and leaf.code=t.atomic_subskill_code
    )
),
resolved as (
  select l.*,
         leaf.code new_leaf_code,
         leaf.name new_leaf_name,
         skill.code new_skill_code,
         skill.name new_skill_name
  from legacy l
  join legacy_map m
    on m.old_primary=l.old_primary
   and m.old_subskill=l.old_subskill
  join public.academic_skill_registry_nodes leaf
    on leaf.code=m.target_leaf_code
   and leaf.node_type='subskill'
   and leaf.status='active'
  join public.academic_skill_registry_nodes skill
    on skill.id=leaf.parent_id
   and skill.node_type='skill'
   and skill.status='active'
)
insert into public.verified_question_diagnostic_taxonomy(
  question_id,assessment_item_id,curriculum_mapping_id,question_content_hash,
  scope_code,objective_code,package_version,taxonomy_version,
  primary_skill_code,primary_skill_name,atomic_subskill_code,atomic_subskill_name,
  assessment_process_code,cognitive_process,evidence_statement,secondary_skill_codes,
  confidence_score,review_status,human_review_required,review_reason,
  supersedes_taxonomy_id,reviewed_by_authority,taxonomy_hash
)
select
  question_id,assessment_item_id,curriculum_mapping_id,question_content_hash,
  scope_code,objective_code,'bh-english-core-v1',
  'bh-english-core-v1-bank-'||substr(question_content_hash,1,12),
  new_skill_code,new_skill_name,new_leaf_code,new_leaf_name,
  assessment_process_code,cognitive_process,evidence_statement,'{}'::text[],
  confidence_score,'approved',false,
  'Full English bank canonical migration from legacy taxonomy: '||
    primary_skill_name||' > '||atomic_subskill_name,
  id,'Brains Heist Platform Superadmin · Full English Registry Migration 2026-09-24',''
from resolved
where not exists (
  select 1
  from public.verified_question_diagnostic_taxonomy successor
  where successor.supersedes_taxonomy_id=resolved.id
    and successor.review_status='approved'
    and not successor.human_review_required
);

do $audit$
declare
  v_legacy_count integer;
begin
  select count(*) into v_legacy_count
  from private.active_verified_question_diagnostic_taxonomy t
  join public.questions q on q.id=t.question_id
  join public.academic_subjects subj on subj.id=q.academic_subject_id
  where lower(trim(coalesce(subj.code,subj.name)))='english'
    and not exists (
      select 1
      from public.academic_skill_registry_nodes leaf
      join public.academic_skill_registry_nodes skill on skill.id=leaf.parent_id
      join public.academic_skill_registry_versions v on v.id=leaf.registry_version_id
      where v.code='bh-english-core-v1'
        and skill.code=t.primary_skill_code
        and leaf.code=t.atomic_subskill_code
    );

  if v_legacy_count <> 0 then
    raise exception 'english_taxonomy_migration_incomplete: % active legacy rows remain',v_legacy_count;
  end if;
end;
$audit$;
